### ISSUE TITLE
FR: change underscore to dash

### ISSUE THREAD

**Issue by Mariusthvdb** [arallsopp/hass-hue-icons#1]
HI, first of all, great work! nice to see the hue icons easily available in HA.

please let ,me suggest to change the icon names to use a dash between words instead of the underscore? This makes it more in lign with HA icon naming in general:
```
hue:wall-flood
```
versus 
```
hue:wall_flood
```

just that bit nicer to the eye

**Comment by arallsopp** [comment]
That’s a fair observation. Thanks for the pointer. I’ll extend the script to be backwards compatible for all the current entries, and look to implement this in the next release.

**Comment by arallsopp** [comment]
Thanks for the versioning tip. That’s in, as is the underscore to dash suggestion. 

Makes it so much easier to spot which release I’m running when on my desktop.
