### ISSUE TITLE
Hue Beyond

### ISSUE THREAD

**Issue by alvinchen1** [arallsopp/hass-hue-icons#10]
**What is the specific model of hue fixture/bulb that you want an icon for**

Hello, great work, could we get an icon for the Hue Beyond? 

**Provide a URL that points to an image of this fixture/bulb**

https://www.philips-hue.com/en-in/p/hue-white-and-color-ambiance-beyond-table-lamp/7120231I7

**Additional context**

**Comment by arallsopp** [comment]
Family day today, but will be on it later! :)

cheers.

**Comment by alvinchen1** [comment]
Thanks!  Cheers!

**Comment by arallsopp** [comment]
Hey @alvinchen1. I'm not really familiar with how this light looks when its on... 

Can you tell me whether A, B or C will work best for how it behaves?

![image](https://user-images.githubusercontent.com/2462104/126046167-26f5b1b7-c994-42e7-9617-3974b68b5a23.png)

**Comment by alvinchen1** [comment]
It actually has two lights in it, one up and one down, so it has four total states, both off, both on, up on, and down on.  For the purposes of this, I think it probably makes the most sense to offer #1.

None of your other icons show different states, (ON/OFF), so why should this one be any different? Even though it has two lights in it and four total states.  If you do consider offering different icons for on or off in the future (not suggesting that you do), then it would be hue:beyond = 1 (both are on), hue:beyond-up = 2 (up is on), and hue:beyond-down = 3 (down is on)., and maybe have one that is hue:beyond-off where everything is solid (both off).

Hope that makes sense.

**Comment by arallsopp** [comment]
Got you. Perfectly explained. It gets complicated because the bit that lights up on the icon is the bit shaded black. So if I do go for states, they're the reverse of what we'd expect :)

I think I'll go with option 1, but will add the others as -alt variants.

**Comment by alvinchen1** [comment]
Yup, sounds great. I personally would probably use the -alt variants to indicate which one is on/off...Thanks again.

**Comment by arallsopp** [comment]
@alvinchen1: There you go. v.1.0.28 has it.

| Icon | Name | Icon | Name 
| :--- | :--- | :--- | :--- |
| ![hue:beyond-down](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/beyond-down.svg)| hue:beyond-down | ![hue:beyond-solid](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/beyond-solid.svg)| hue:beyond-solid |
| ![hue:beyond-up](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/beyond-up.svg)| hue:beyond-up | ![hue:beyond](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/beyond.svg)| hue:beyond |

**Comment by arallsopp** [comment]
Having thought on this, I think I named up and down the wrong way around. Again, tricky, as the solid bit will be the bit that lights up when it's used with state color. 


I'm wondering if it'd be better to rename them:


| Icon | Name | Icon | Name 
| :--- | :--- | :--- | :--- |
| ![hue:beyond](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/beyond.svg)| hue:beyond | ![hue:beyond-solid](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/beyond-solid.svg)| hue:beyond-solid |
| ![hue:beyond-up](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/beyond-up.svg)| hue:beyond-solid-top| ![hue:beyond-solid-bottom](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/beyond-down.svg)| hue:beyond-solid-bottom|

**Comment by alvinchen1** [comment]
Makes sense to me. I am one of those using the old icon names, but happy to change to what you feel is best.

**Comment by arallsopp** [comment]
Hey @alvinchen1.

Just to let you know, I'm going to be stopping development effort on this for a while, as my work is being stolen by [another repo](https://github.com/elax46/custom-brand-icons/) without permission, in breach of the CC license, and without any attempt to give credit to the original author or those who've helped me.

This project has always been offered as free to use, and for the benefit of the home assistant community rather than any individual. More than half of this library is the 80 or so original icons I've created, drawn and gifted to the home assistant community. Those icons are all original works, driven by requests from people like you, taken on as a willing task, and shared here on a non commercial basis for all who want them.

It felt good to give back, and the work was a reward in itself, but finding the icons I'm creating being offered elsewhere, proffered up alongside a request for paypal donations to support their creation is really not in the spirit of the community. 

The whole experience has left a bad taste in my mouth, and I'll be stepping away for some time.

Cheers, and thanks for your interest.

Andy.

**Comment by alvinchen1** [comment]
Hey man, that's sucks.   Really appreciate all your help and work on this.  And that totally sucks that they sourced it from you and monetized it. Especially curbing on your work.    If you wanted to pull this private, I would totally understand doing so.

**Comment by arallsopp** [comment]
Thanks @alvinchen1.  I don't want to do anything that could be punitive for the community, and making the icons harder to discover or find would only really hurt those I'd hoped to help. It also risks leaving the illegitimate repo as the only public source for the works I've created, which isn't a great legacy for things. 

When you share something online, there's always a risk that someone will try to steal what's offered for free. I don't want the acts of a few solitary morons to ruin it for everyone else, but they do suck the joy out of it.

I'll be back, but with a little less faith in people.

**Comment by alvinchen1** [comment]
Yup, I totally agree.  You are in an unenviable situation with that and I completely understand.  Again, thank you for what you did and taking the highroad on this situation.

**Comment by alvinchen1** [comment]
Hey @arallsopp, awesome call out from the lead developer for HA today.  Saw your mention on the 2021.11 post.  Cause you do good work!

**Comment by arallsopp** [comment]
Hey @alvinchen1. Thanks for the nudge. Wow. I feel quite proud! Goodness!
