### ISSUE TITLE
ikea ps 2014 lamp

### ISSUE THREAD

**Issue by djdanip** [arallsopp/hass-hue-icons#101]
**What is the specific model of hue fixture/bulb that you want an icon for**
ikea ps 2014 lamp

**Provide a URL that points to an image of this fixture/bulb**
https://ibb.co/SJ8JJh0

**Additional context**

**Comment by arallsopp** [comment]
Howdo. Unless I've misunderstood, that's not a hue lamp, so I'm afraid I won't be adding it to this repo. Hass-hue-icons is for Philips Hue and Friends of Hue lights only. 

Sorry. Happy to review if I have this wrong.
