### ISSUE TITLE
Extra group icons

### ISSUE THREAD

**Issue by mdawsonuk** [arallsopp/hass-hue-icons#102]
**What is the specific model of hue fixture/bulb that you want an icon for?**

There are many different `hue:*group*` options, some notable ones for me which are missing are a group with a sultan bulb and a Go, and a filament bulb and a Go. Would it be possible to add these? 

Loving the icons so far 😃 
Many thanks!

**Comment by arallsopp** [comment]
Sultan and go, filament and go... OK. Worth a try. Check back in the morning and see where I've got to. :)

**Comment by arallsopp** [comment]
![image](https://user-images.githubusercontent.com/2462104/143506598-b6b2497a-f7b5-4fb7-b601-22787387b68e.png)
Hmm.. They don't sit well together. I may try putting the go in front.

**Comment by mdawsonuk** [comment]
I'm guessing the Go to the left obscures the fact it's a Go in the first place?

**Comment by arallsopp** [comment]
Does a bit. I think this is probably better though:

![image](https://user-images.githubusercontent.com/2462104/143506740-0f0f3b99-b0aa-4637-b0c6-44d8ae751a52.png)

Which do you prefer? They're your icons, so you get to choose :)

**Comment by mdawsonuk** [comment]
Am I allowed to say both? 👀

**Comment by arallsopp** [comment]
Lol. Yeah, OK. I'll run up the four, unless filament forces me one way or another :)

**Comment by arallsopp** [comment]
Thanks for the suggestion. Your new icons (yes, all four of them!) are in in release [v.1.1.11](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.11).

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-go-sultan](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-go-sultan.svg)| hue:bulb-group-go-sultan|
| ![hue:bulb-group-filament-go](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-filament-go.svg)| hue:bulb-group-filament-go|
| ![hue:bulb-group-sultan-go](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-sultan-go.svg)| hue:bulb-group-sultan-go|
| ![hue:bulb-group-go-filament](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-go-filament.svg)| hue:bulb-group-go-filament|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 183 custom icons has been driven by a community request just like yours, and stars help others find this repo.

### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by mdawsonuk** [comment]
Awesome job - thanks @arallsopp!

**Comment by arallsopp** [comment]
My pleasure. Enjoy.
