### ISSUE TITLE
Request - new icon - Philips Hue Beyond - ceiling lamp

### ISSUE THREAD

**Issue by njguyuk891** [arallsopp/hass-hue-icons#103]
Hi 

Not sure if this is the correct place to ask for a request but could you consider adding a icon for 
Philips Hue Beyond - ceiling lamp 

link here in case you need a screen shot - https://ilamparas.co.uk/philips-hue/philips-hue-beyond-ceiling-lamp--8718696121870/

Thanks

**Comment by arallsopp** [comment]
Morning!  This is exactly the place to make that request. Thanks for the suggestion. I'm on it.

**Comment by arallsopp** [comment]
Its coming... Looks like it only has on or off, so will just make a solid and an outlined one.

![image](https://user-images.githubusercontent.com/2462104/143682417-7d3b0255-2b4d-4914-8068-0f27f8ad4065.png)

**Comment by arallsopp** [comment]
Thanks for the suggestion, @njguyuk891 njguyuk891. It'll be in release [v.1.1.12](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.12) later today, as there's another request to bundle in and family duties first!

| Icon | Name |
| :--- | :--- |
| ![hue:ceiling-beyond](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-beyond.svg)| hue:ceiling-beyond|
| ![hue:ceiling-beyond-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-beyond-alt.svg)| hue:ceiling-beyond-alt|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 185 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by arallsopp** [comment]
Released, and closing with thanks.
