### ISSUE TITLE
Sultan Bulb Group

### ISSUE THREAD

**Issue by mdawsonuk** [arallsopp/hass-hue-icons#104]
**What is the specific model of hue fixture/bulb that you want an icon for**

Can't believe I didn't mention this in #102, but a group comprised just of `hue:bulb-sultan` doesn't currently exist.

**Comment by arallsopp** [comment]
Lol. Got you. Don't worry about it. Any others you come up with are fair game.

**Comment by arallsopp** [comment]
Hey! Wait a sec. Isn't the default hue:bulb group actually a pair of sultans?

| Icon | Name | 
| :--- | :--- |
| ![hue:bulb-group](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/bulb-group.svg)| hue:bulb-group | 
| ![hue:bulb-sultan](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/bulb-sultan.svg)| hue:bulb-sultan |

**Comment by mdawsonuk** [comment]
Looks like it is - I'm blind apparently. 

Can you do synonyms for icons though, as given the other names, it feels like hue:bulb-group-sultan should give the same icon?

**Comment by arallsopp** [comment]
That's a fair point. I know this was something the HA team were looking to add support for. I wouldn't want to inflate the resource size to hold a copy of the image, but if I can find a way to tag under another label, I'll do that.

**Comment by mdawsonuk** [comment]
Looking at the code it might require some refactoring on your part, would it be feasible to have a separate HUE_ICONS_NAME_MAP map which then maps the values to the HUE_ICONS_MAP? I can't find any documentation on synonyms for icons but I'll keep looking

**Comment by arallsopp** [comment]
The iconpicker pull request has the detail. I'm planning a refactor where I can keyword as Philips, light, security, etc.

**Comment by mdawsonuk** [comment]
Awesome, let me know if I can help out in any way :)

I'll close this issue for now, but I'll keep an eye out for any refactoring

**Comment by arallsopp** [comment]
One release coming up with refactored structure to support keywords. Thanks @mdawsonuk!
