### ISSUE TITLE
Icon Request Bridge 2.0

### ISSUE THREAD

**Issue by fanaticDavid** [arallsopp/hass-hue-icons#106]
This may be an unusual request, but I'd love to have an icon for the Philips Hue Bridge 2.0.

**What is the specific model of hue fixture/bulb that you want an icon for**

In the Hue app, the model is listed as BSB002.

**Provide a URL that points to an image of this fixture/bulb**

https://www.assets.signify.com/is/image/PhilipsLighting/1731ca9fc8d24cc99b8dac0e00d41c4d

**Additional context**

I track the online/offline state of a number of my network devices, including my Philips Hue Bridge 2.0. This icon would be used for the related entity.

**Comment by arallsopp** [comment]
Good call. Am on it.

**Comment by arallsopp** [comment]
Hey there, @fanaticDavid. Realised Hue actually provides these icons in their developer kit and that I'd missed them on my first time through. Apologies for that. Thanks for the use case and suggestion.

| Icon | Name | 
| :--- | :--- | 
| ![hue:bridge-v1](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/bridge-v1.svg)| hue:bridge-v1 |
| ![hue:bridge-v2](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/bridge-v2.svg)| hue:bridge-v2 |

They'll be in release [v.1.1.13](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.13).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 185 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by fanaticDavid** [comment]
Hey @arallsopp. Thank you so much for the quick addition, and I'm glad I was able to make a useful suggestion after all 😏

**Comment by arallsopp** [comment]
Always, mate. This repo is driven by people like you asking for icons. Every time someone asks, it just makes it better :)
