### ISSUE TITLE
[Icon Request] hanging version of hue:bulb-filament-alt 

### ISSUE THREAD

**Issue by mailalhv** [arallsopp/hass-hue-icons#107]
**What is the specific model of hue fixture/bulb that you want an icon for**

The already existing "[hue:bulb-filament-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-filament-alt.svg)" as a hung version, please.

**Additional context**
I do have the hue:bulb-filament-hung mixed with the hue:bulb-filament-alt in a ceiling mounted hanging lamp and thus would like to have a hanging version of this smaller one as well. If it would be possible to have a group of these two filament bulbs as well this would be the icing on the cake ;-)

**Comment by arallsopp** [comment]
Howdo @mailalhv. Just to confirm, you'd like:

- a hung version of bulb-filament-alt
- a group of a,b,c, or other?
  a. bulb-filament-alt pair?
  b. bulb-filament-alt-hung pair?
  c. bulb-filament-alt-hung-with-bulb-filament-hung?

**Comment by arallsopp** [comment]
Here's where we are so far, representing 1 and C above, @mailalhv. If this meets your requirement, let me know and I'll create a new release with these in. If you intended something else, just let me know and I'll aim for that and release afterwards.

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-filament-alt-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-filament-alt-hung.svg)| hue:bulb-filament-alt-hung|
| ![hue:bulb-group-filament-filament-alt-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-filament-filament-alt-hung.svg)| hue:bulb-group-filament-filament-alt-hung|

**Comment by arallsopp** [comment]
Here's a reversal on that second one, just incase you prefer the other primary.

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-filament-alt-filament-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-filament-alt-filament-hung.svg)| hue:bulb-group-filament-alt-filament-hung|

**Comment by mailalhv** [comment]
Yes, that's absolutely perfect.
Thank you very much

**Comment by arallsopp** [comment]
Glad to hear. All have been added to [v.1.1.14](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.14) which is available now. :)

Thanks for the suggestion and star :)
