### ISSUE TITLE
Icon aliases

### ISSUE THREAD

**Issue by mdawsonuk** [arallsopp/hass-hue-icons#108]
The Icon picker supports tags and aliases for searching similarly named or related items. This involves the addition of a keywords string array which can be added to custom icon sets.

PR related to adding support for aliases can be found at home-assistant/frontend#10425

Opening this issue as it arose in #104 and for collating information

**Comment by arallsopp** [comment]
Yep. I read that. I have a version here that uses the keywords, but it only shows each icon twice (my dash uses the same icon about 7 times in one room). Definitely something I need to explore a bit more.

**Comment by arallsopp** [comment]
Not sure if @piitaya can help?

I based my code upon [their sample](https://github.com/home-assistant/frontend/pull/10399#issuecomment-953301513), but when I test it in my HA instance, I find many of the icons are missing, even if the identical icons are appearing elsewhere in the same screen. Probably easier to show than describe, so here's a video: https://youtu.be/f8fPgZU65hI

The code in the [pull request](https://github.com/home-assistant/frontend/pull/10399) looks functionally identical to that which I've used, but perhaps I've missed something along the way?

```
async function getIcon(name) {
  return {path: HUE_ICONS_MAP[name]?.path};
}
async function getIconList() {
  return Object.entries(HUE_ICONS_MAP).map(([icon, content]) => ({
    name: icon,
    keywords: content.keywords,
  }));
}
window.customIcons = window.customIcons || {};
window.customIcons["hue"] = { getIcon, getIconList };
```

The script in full is accessible in the with-keywords branch, [here](https://github.com/arallsopp/hass-hue-icons/blob/with-keywords/dist/hass-hue-icons.js).

@piitaya: If you can give any pointers, please do.

**Comment by arallsopp** [comment]
Thanks for raising this, @mdawsonuk.

Hopefully its easier to locate the icons you need now.  Feature example here: https://youtu.be/1KgS5QCXeto

**Comment by mdawsonuk** [comment]
Thanks @arallsopp, awesome work as always
