### ISSUE TITLE
Icon Request [hue:bulb-group-candle-lightstrip]

### ISSUE THREAD

**Issue by thijselblaso** [arallsopp/hass-hue-icons#110]
It would be nice to have the icon: hue:bulb-group-candle-lightstrip

Can you replace the hue:bulb-sultan (of the hue:bulb-group-sultan-lightstrip icon) with a hue:bulb-candle icon?

![Screenshot 2021-12-02 at 10 09 11](https://user-images.githubusercontent.com/38098396/144391978-d37acd79-f2eb-40e7-b973-deab81557fbf.png)

**Comment by arallsopp** [comment]
Am on it. Thanks for the suggestion, @thijselblaso

**Comment by arallsopp** [comment]
Here's the plan:
![image](https://user-images.githubusercontent.com/2462104/144631167-d5d4a174-c8c3-48c7-a390-3ca8b4309ff9.png)

**Comment by arallsopp** [comment]
Thanks. It'll be in release [v.1.1.15](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.15). Don't forget to star the repo if you want to help others find it.

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-candle-lightstrip](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-candle-lightstrip.svg)| hue:bulb-group-candle-lightstrip|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 189 custom icons has been driven by a community request just like yours, and stars help people find this repo.

### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
