### ISSUE TITLE
Icon Request [name of fixture]

### ISSUE THREAD

**Issue by Knax49** [arallsopp/hass-hue-icons#111]
Icon for the Nanoleaf Light Panels and ESPHome would be great... 

ESPHome:
https://esphome.io/_images/logo.png

Nanoleaf:
https://major-tech.de/wp-content/uploads/2018/07/Bildschirmfoto-2018-07-31-um-13.07.15.png

<!--Add any other context for your icon request here.--
![download](https://user-images.githubusercontent.com/69388811/144643662-a6f784fe-0b75-49f2-be18-a2edd7c13db9.jpg)
>

**Comment by arallsopp** [comment]
Hmmm.  Neither of those are really hue icons, I'm afraid. Both worthy projects in their own right, but not really in scope for this repo, I'm afraid.
