### ISSUE TITLE
Icon Request [Calla]

### ISSUE THREAD

**Issue by svhelge** [arallsopp/hass-hue-icons#112]
**What is the specific model of hue fixture/bulb that you want an icon for**
Calla - 1742030P7

**Provide a URL that points to an image of this fixture/bulb**
https://www.philips-hue.com/no-no/p/hue-white-and-color-ambiance-calla-utendors-sokkel/1742030P7

**Additional context**

**Comment by arallsopp** [comment]
Pretty sure that's in as a bollard. Leave it with me.

**Comment by arallsopp** [comment]
Yep, best bet is to use 

| Icon | Name | 
| :--- | :--- |
![hue:bollard](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/bollard.svg)| hue:bollard |

If I get the alias working, it'll come up as calla in future versions also.

**Comment by arallsopp** [comment]
Closed. I've added the keyword 'calla' to this bollard lamp in version 1.2.0. 

Thanks for the suggestion.
