### ISSUE TITLE
Icon Request [hue:bulb-group-filament-alt-hung]

### ISSUE THREAD

**Issue by trancefam** [arallsopp/hass-hue-icons#113]
**What is the specific model of hue fixture/bulb that you want an icon for**
Hello, thank you for this wonderful repo. I was hoping to get the "hanging" version of 2 oval shaped filament bulbs.

**Provide a URL that points to an image of this fixture/bulb**

![image](https://user-images.githubusercontent.com/26947075/146845917-11f65d5a-ee70-458a-9ebf-1bbf707c9f66.png)
The hanging version of the above. Maybe name `hue:bulb-group-filament-alt-hung`?
**Additional context**
Thank you!

**Comment by arallsopp** [comment]
Lovely one. On it!

**Comment by arallsopp** [comment]
Thanks for this, @trancefam.

It'll be in release [v.1.1.16](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.16). 

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-filament-alt-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-filament-alt-hung.svg)| hue:bulb-group-filament-alt-hung|

Please let me know if there's anything else you need or would like.

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 190 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by arallsopp** [comment]
Released. :)
