### ISSUE TITLE
Sewing Room Icon Request

### ISSUE THREAD

**Issue by blloveless** [arallsopp/hass-hue-icons#117]
**What is the specific model of hue fixture/bulb that you want an icon for**

**Provide a URL that points to an image of this fixture/bulb**

Something like: 

https://www.freepik.com/free-icon/sewing-machine_745611.htm

**Additional context**

It would just be nice to have an icon for a sewing room as I'm setting up air quality sensors specifically to monitor particulate matter in my wife's sewing room.  Thanks.

**Comment by arallsopp** [comment]
Howdo. This library is for hue icons, really, so I'm not sure a sewing machine fits. There's an excellent fontawesome library that lets you add your own icon files. I can look up the repo if that helps.

**Comment by arallsopp** [comment]
@blloveless: I'm closing this one now. Thomasloven's excellent fontawesome library that lets you add your own SVG files to HomeAssistant is [here](https://github.com/thomasloven/hass-fontawesome). 

Hope your air quality sensor project works out.
