### ISSUE TITLE
Hue Turaco

### ISSUE THREAD

**Issue by PDekker** [arallsopp/hass-hue-icons#119]
**What is the specific model of hue fixture/bulb that you want an icon for**
Hue Turaco sokkel lamp 

**Provide a URL that points to an image of this fixture/bulb**
https://www.amazon.nl/Philips-Hue-Turaco-Sokkellamp-Verlichting/dp/B07BY2BFQM/ref=asc_df_B07BY2BFQM/?tag=nlshogostdde-21&linkCode=df0&hvadid=430527493653&hvpos=&hvnetw=g&hvrand=5349240220562059614&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9064901&hvtargid=pla-466433721550&psc=1

**Additional context**
There is a high and a low variant. I use the low variant.

**Comment by arallsopp** [comment]
Good find! I've never seen these before.

![image](https://user-images.githubusercontent.com/2462104/147953132-0ae78692-9614-4b2f-aaf4-10af364d5e1c.png)
![image](https://user-images.githubusercontent.com/2462104/147953179-93eb6c5d-bb96-4d27-bbb0-3d485e69e95c.png)

I'll take a run at them tonight!

**Comment by arallsopp** [comment]
And the long one alongside. I figure people will probably use the long version unless they have both, then will use the (very) short version to differentiate.

![image](https://user-images.githubusercontent.com/2462104/147960736-c5423cdd-21b0-4439-a071-3a7e44122f69.png)

**Comment by PDekker** [comment]
Looks good! I think I will be using the long one. Since I don’t own a long one, just like you said.

**Comment by arallsopp** [comment]
Thanks @PDekker. Short and tall variants coming up in the next release.

| Icon | Name |
| :--- | :--- |
| ![hue:pillar-turaco-short](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pillar-turaco-short.svg)| hue:pillar-turaco-short|
| ![hue:pillar-turaco-tall](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pillar-turaco-tall.svg)| hue:pillar-turaco-tall|

**Comment by arallsopp** [comment]
Thanks again @PDekker. Closing this now with your icons in last night's release of [v.1.2.1](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.1).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 194 custom icons has been driven by a community request just like yours, and stars help people find this repo.

### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
