### ISSUE TITLE
Icon Request [temperature outside]

### ISSUE THREAD

**Issue by pepsonEL** [arallsopp/hass-hue-icons#120]
Hi
Is any chance to add this icon from this image url ?
https://pl.dreamstime.com/temperaturowa-outside-linii-ikona-image100433538?fbclid=IwAR3FEIoPWcB38KmpAXabVu_aIHgCL0Dx_z9nZFymuhhLOOAtmOPCtBCOFp4
Thanks

**Comment by arallsopp** [comment]
Hmmm... 

I can't really justify ripping the image, but can see that temperature is arguably a hue function if you were using their motion sensors. How about I come up with a temperature based icon that implies the motion sensor housing, indoor and outdoor models?

If you'd rather use the icon linked above, the best way will be to recreate (or trace via a free png to svg service) as an svg file, then use another repo that will let you add icons, such as thomasloven's fontawesome plugin.

**Comment by pepsonEL** [comment]
Could you show me icon about which you write ?

**Comment by arallsopp** [comment]
I was thinking something like this for the indoor:
![image](https://user-images.githubusercontent.com/2462104/148080481-9a2b6a84-e1f5-4c1c-a35f-c170add75daf.png)
![image](https://user-images.githubusercontent.com/2462104/148080511-6e8d3b1d-1213-4519-b67a-db83a7db3afb.png)

**Comment by arallsopp** [comment]
The outdoor version would use the outdoor motion sensor, like this:

![image](https://user-images.githubusercontent.com/2462104/148081134-2df19e02-d4d0-4976-b693-ec081c0be511.png)

**Comment by arallsopp** [comment]
Well, they'll be in v.1.2.2 when it comes. Hopefully this works for you, @pepsonEL? If so, please consider giving the repo a free star :)

| Icon | Name |
| :--- | :--- |
| ![hue:outdoor-motion-sensor-temperature](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/outdoor-motion-sensor-temperature.svg)| hue:outdoor-motion-sensor-temperature|
| ![hue:motion-sensor-temperature](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/motion-sensor-temperature.svg)| hue:motion-sensor-temperature|



### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 196 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by pepsonEL** [comment]
But if i have PNG you can transform it 
![NicePng_temperature-icon-png_2975832](https://user-images.githubusercontent.com/71824185/148133816-fb0fa15b-a54e-4088-8f67-f267b0ef33fa.png)
?

**Comment by arallsopp** [comment]
https://www.pngtosvg.com/ will convert it. Fontawesome plug-in will let you use your own svg as an icon. 

The icon you're trying to use isn't really anything to do with Philips hue, so I can't add it to this repo. 

The only hue devices that support temperature are the motion sensors. I've drawn new icons for them to include thermometers. 

You're welcome to use these, or to modify them as you see fit.

**Comment by arallsopp** [comment]
Closing with the hue motion sensor icons added to v.1.2.2

| Icon | Name |
| :--- | :--- |
| ![hue:motion-sensor-temperature](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/motion-sensor-temperature.svg)| hue:motion-sensor-temperature|
| ![hue:outdoor-motion-sensor-temperature](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/outdoor-motion-sensor-temperature.svg)| hue:outdoor-motion-sensor-temperature|
| ![hue:ceiling-xamento](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-xamento.svg)| hue:ceiling-xamento|
