### ISSUE TITLE
Icon Request group icon for pillar-turaco

### ISSUE THREAD

**Issue by emilezweep** [arallsopp/hass-hue-icons#122]
**What is the specific model of hue fixture/bulb that you want an icon for**

Is it possible to create an group icon for hue:pillar-turaco-short and hue:pillar-turaco-tall?

**Provide a URL that points to an image of this fixture/bulb**

**Additional context**

**Comment by arallsopp** [comment]
I'll take a look. Stand by please :)

**Comment by arallsopp** [comment]
![image](https://user-images.githubusercontent.com/2462104/148469028-5fa56909-64df-4696-b10a-c3042d7616c9.png)
Coming up.

**Comment by arallsopp** [comment]
Thanks for the suggestion, @emilezweep.

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-pillar-turaco-short-tall](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-pillar-turaco-short-tall.svg)| hue:bulb-group-pillar-turaco-short-tall|

It'll be in release [v.1.2.3](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.3) within about 5 minutes.

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 198 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
