### ISSUE TITLE
HUE Devote Pendant

### ISSUE THREAD

**Issue by sesardelaisla** [arallsopp/hass-hue-icons#124]
Any chance for the HUE Devote pendant to be added, please?
https://www.philips-hue.com/en-gb/p/hue-white-ambiance-colgante-devote/8719514341234

![image](https://user-images.githubusercontent.com/81921573/149997618-8509e74a-782d-4266-a01f-03bceef97a38.png)

**Comment by arallsopp** [comment]
Yep. Will have a look to see what variants there are

**Comment by sesardelaisla** [comment]
Thank you! :) As far as I know, there are no variants. Just this single model. Furthermore, I think there are no additional colours (only white).

**Comment by arallsopp** [comment]
From my understanding it's a housing for an E27 so people could add colour bulbs after purchase. 

Every time I see a photo, there are 3 in a row so I'll do a single and a group of 3 once I'm at my desk.

**Comment by sesardelaisla** [comment]
Yup. It is an E27 housing indeed. The box comes with a White Ambiance bulb, but you can use a Colour Ambiance one. I have two of them installed over my kitchen bar, so it would be great if you can also add a group of two. However, some people may have four, five... so if you prefer not to do so many variants, I'll understand it. I can use the group of three for my couple. Whatever you eventually do, I will appreciate it. :)

**Comment by arallsopp** [comment]
![image](https://user-images.githubusercontent.com/2462104/150020056-91761a77-5fd3-4d9f-b194-c8abb0bdeb8a.png)
I'm struggling to find a decent picture of this one, and where the bulb begins. Is the left or right icon better, do you think? Should I straighten the edges a little more?

**Comment by arallsopp** [comment]
![image](https://user-images.githubusercontent.com/2462104/150020994-6af0d65d-fa88-43bf-9578-65500dc1d992.png)
I'm leaning towards option 3, I think.

**Comment by arallsopp** [comment]
![image](https://user-images.githubusercontent.com/2462104/150022854-fa21c5bf-1ece-42d4-9ff6-9a9fd3b2d850.png)
Ok. Here's what I'm going with :)

**Comment by arallsopp** [comment]
These will be in the next release.

| Icon | Name |
| :--- | :--- |
| ![hue:pendant-devote](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-devote.svg)| hue:pendant-devote|
| ![hue:pendant-devote-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-devote-two.svg)| hue:pendant-devote-two|
| ![hue:pendant-devote-three](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-devote-three.svg)| hue:pendant-devote-three|

**Comment by arallsopp** [comment]
They're up. Please consider starring this repo if you find it useful, @sesardelaisla. Stars help other users discover hass-hue-icons and help drive the library forwards.

Cheers!

**Comment by sesardelaisla** [comment]
Thanks you @arallsopp !! The design choice you made is perfect! Thank you so much for your work! Cheers!
