### ISSUE TITLE
HUE Struana Bathroom Ceiling Light

### ISSUE THREAD

**Issue by sesardelaisla** [arallsopp/hass-hue-icons#125]
Would it be possible to add this specific ceiling light model, please? There are some similar icons in the list, but I think there is not one for this specific model. Thanks!

https://www.philips-hue.com/en-gb/p/hue-white-ambiance-plafon-para-banos-struana/8719514341012

![image](https://user-images.githubusercontent.com/81921573/150019259-46ae6884-6dbf-4d13-b8b2-14e430617bdb.png)

**Comment by arallsopp** [comment]
Yes, I'll add that to the next release alongside devote. Cheers!

**Comment by arallsopp** [comment]
Coming up...
![image](https://user-images.githubusercontent.com/2462104/150029752-807c1d35-e52b-46d0-a62b-281af1e1810c.png)

**Comment by arallsopp** [comment]
Now with added moustache. Looks like a pringles can, but I prefer it :)

![image](https://user-images.githubusercontent.com/2462104/150030183-5039cf28-6c4c-4b7f-984e-0a35b7a06370.png)

**Comment by arallsopp** [comment]
Thanks again for the suggestion, @sesardelaisla. 

struana will be in release [v.1.2.4](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.4) in the next five minutes, along with your devote request


| Icon | Name |
| :--- | :--- |
| ![hue:struana](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/struana.svg)| hue:struana|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 202 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by arallsopp** [comment]
Thank you for that feedback. The alternate angle is much appreciated. I'll make the moustache version an -alt suffix in the next release, and give you a round one by default from that point forwards:)

**Comment by arallsopp** [comment]
Cheers, @sesardelaisla. Here's a preview of what'll come in the next release. (You may need a cache bust to see the changed icon)

| Icon | Name |
| :--- | :--- |
| ![hue:struana](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/struana.svg)| hue:struana|
| ![hue:struana-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/struana-alt.svg)| hue:struana-alt|

**Comment by sesardelaisla** [comment]
Both versions look great. Thanks for asking!
