### ISSUE TITLE
Par38 Dual Flood Light Socket Fixture

### ISSUE THREAD

**Issue by bryeartem** [arallsopp/hass-hue-icons#126]
I have my PAR38 flood lights in a simple old dual socket fixture.  I was hoping maybe you could make something that represents 2 flood light bulbs in that type of fixture.  As i mentioned before having the icons look like the light they actually represent makes my UI so much more appealing. 
Sorry if this is getting too far of the realm of "Hue" fixtures.  I understand if you don't want to deviate that much

This is a URL to the type of fixture.. obviously the hue smart bulbs look a little different i linked those as well

https://www.amazon.com/Lithonia-Lighting-OFTH-300PR-120/dp/B001QGIUDG/ref=sxin_13_pa_sp_search_thematic_sspa?crid=U10MU5X8UBNO&cv_ct_cx=par38+fixture&keywords=par38+fixture&pd_rd_i=B001QGIUDG&pd_rd_r=67d8fce1-f361-4792-a68e-cf7a49cd497b&pd_rd_w=ITckJ&pd_rd_wg=0lE93&pf_rd_p=4ad71b32-b810-4124-8735-d02a39478d0c&pf_rd_r=A5GPV55KXS5BVWP35WCC&qid=1642901774&sprefix=par38+fi%2Caps%2C161&sr=1-2-a73d1c8c-2fd2-4f19-aa41-2df022bcb241-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFMSjc4MEpDSFFCUUwmZW5jcnlwdGVkSWQ9QTAyNzU5ODYzN1lLRDdVQ0JRSTcyJmVuY3J5cHRlZEFkSWQ9QTAyMTIxNjkyRllRNVpJWjZGVzE3JndpZGdldE5hbWU9c3Bfc2VhcmNoX3RoZW1hdGljJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==

https://www.amazon.com/Philips-Outdoor-Hue-PAR-38-476812/dp/B07D9XL63W/ref=sr_1_2?gclid=CjwKCAiA866PBhAYEiwANkIneCHqnlsKY-Z6paOpTdu6YcRkLQ2v1uOXikaqOWg2qEfJQ2i06NtjoRoCpOoQAvD_BwE&hvadid=410010218154&hvdev=c&hvlocphy=9005523&hvnetw=g&hvqmt=e&hvrand=17484531647088789592&hvtargid=kwd-474849320282&hydadcr=8433_11337195&keywords=philips%2Bhue%2Bpar38&qid=1642901733&sr=8-2&th=1

**Additional context**

**Comment by arallsopp** [comment]
Good call. I'll try to run up an alternate bulb grouping for them. Am travelling this week so mightn't be quick.

**Comment by arallsopp** [comment]
How about this for a bulb group par-38?

![image](https://user-images.githubusercontent.com/2462104/151723933-76ad3a6c-64cb-40ac-a12c-9bab73554139.png)

**Comment by arallsopp** [comment]
Ah... this is better. Going with the added circle behind it.

![image](https://user-images.githubusercontent.com/2462104/151724144-04b74524-9a25-4358-a4a5-5ca1256451f3.png)

**Comment by arallsopp** [comment]
OK. That'll be in forthcoming release [v.1.2.6](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.6).

I've a few others to squeeze in there, so give it an hour or so for the release.

Cheers!

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 207 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by bryeartem** [comment]
Looks absolutely perfect! You’re the best!  Thanks for your time.

**Comment by arallsopp** [comment]
No problem, @bryeartem. Glad to be able to help.
