### ISSUE TITLE
3 icon requests (bollard / appear / pillar)

### ISSUE THREAD

**Issue by Patrick1610** [arallsopp/hass-hue-icons#127]
Hi, I really like the Hue icons to finish my frontend, I am missing a few that I would really appreciate, can you try to make those? 

I would like to have a group icon with one of each of the following icons:
- hue:bollard
- hue:wall-appear
I don't know which order (left/right icon) looks nicer but based on your icons you have an eye for that!

Also, I would like to have a 2 and 3 group of the hue:pillar-spot icon. 

My last request may not be an existing hue product, but an icon I could really use. I have fixtures that look like the hue:wall-appear icon, but without the upper spot. Could you make an icon like the hue:wall-appear where the top levels out with the mounting bracket?

Thanks a lot for making these nice icons 🙏🏼 

Kind regards, Patrick

**Comment by Patrick1610** [comment]
One additional request:
Could you make an alternative attic icon that is the same style as the hue:downstairs and hue:upstairs icons? So black down/upstairs, white attic?

**Comment by arallsopp** [comment]
Yep. I'm travelling this week but will jump to it when I'm back.

**Comment by Patrick1610** [comment]
That's great 😃

**Comment by arallsopp** [comment]
> Also, I would like to have a 2 and 3 group of the hue:pillar-spot icon.

The two is easy enough. The three gets a bit tight on space, so I'm proposing the below.

![image](https://user-images.githubusercontent.com/2462104/151724889-aa19b838-7fea-4937-b307-42c1c15f197a.png)

**Comment by arallsopp** [comment]
Thanks for the suggestion. These will be in release [v.1.2.6](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.6) when its up. Give it an hour or so, as I have the other requests to squeeze in yet.

| Icon | Name |
| :--- | :--- |
| ![hue:pillar-spot-2](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pillar-spot-2.svg)| hue:pillar-spot-2|
| ![hue:pillar-spot-3](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pillar-spot-3.svg)| hue:pillar-spot-3|

**Comment by arallsopp** [comment]
> I would like to have a group icon with one of each of the following icons:
> 
> * hue:bollard
> * hue:wall-appear

They're wildly different sizes in reality,  so I'm tempted to just make them flat iconic rather than the normal receding into the distance style.

![image](https://user-images.githubusercontent.com/2462104/151725699-f01444c9-5c71-4841-95c8-eb096bd7896c.png)

**Comment by arallsopp** [comment]
This will be added to release [v.1.2.6](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.6) when its up. Am looking at the remaining requests now.

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-bollard-wall-appear](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-bollard-wall-appear.svg)| hue:bulb-group-bollard-wall-appear|

**Comment by arallsopp** [comment]
> 
> ~I would like to have a group icon with one of each of the following icons:~
> 
> ~* hue:bollard~
> ~* hue:wall-appear~
> ~  I don't know which order (left/right icon) looks nicer but based on your icons you have an eye for that!~
> 
> ~Also, I would like to have a 2 and 3 group of the hue:pillar-spot icon.~
> 
> My last request may not be an existing hue product, but an icon I could really use. I have fixtures that look like the hue:wall-appear icon, but without the upper spot. Could you make an icon like the hue:wall-appear where the top levels out with the mounting bracket?

Hmmm... That'll need some more thought. I may have to create 'custom' icon support as its not really hue. Hmmm...

Well, the rest is in, so let's get this release out of the way first.

Andy.

**Comment by Patrick1610** [comment]
They're awesome! I think it's perfect to just have the bollard and appear the same size, the appear would become really small otherwise. 

I understand that the non hue light is not easy to implement in a Hue icon pack, so no problem at all! Is that the same with the attic icon I wrote about in the comments, or is that a possibility to add? 

Thanks for your work 🙏🏼

**Comment by arallsopp** [comment]
Howdo @Patrick1610. Apologies for the lag. I've been out of range for a while.

Your alt attic icon will arrive in release [v.1.2.10](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.10), which will likely be published in the coming days. It'll look like the below:

| Icon | Name |
| :--- | :--- |
| ![hue:room-attic-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-attic-alt.svg)| hue:room-attic-alt|

**Comment by Patrick1610** [comment]
Thanks a lot Andy! I see the update 🙏🏼
