### ISSUE TITLE
Wall Sconce with Switch

### ISSUE THREAD

**Issue by bryeartem** [arallsopp/hass-hue-icons#128]
**What is the specific model of hue fixture/bulb that you want an icon for**

Sorry to be super needy but you do such a great job... when setting the icon on some more bulbs I realized I have a couple fixtures that I cant really find a good match for.  

**Provide a URL that points to an image of this fixture/bulb**
https://www.homedepot.com/p/Design-House-Village-1-Light-Indoor-Dimmable-Wall-Sconce-with-Frosted-Flute-Glass-with-Twist-On-Off-Switch-Oil-Rubbed-Bronze-505115/202500708

https://www.homedepot.com/p/Design-House-Lydia-1-Light-Matte-Black-Indoor-Dimmable-Wall-Sconce-with-Frosted-Glass-and-Twist-On-Off-Switch-588814-BLK/318683625

**Additional context**
Maybe some halfway variation between to the two? So it would suffice for people with either style.  And apologies if I missed an existing icon that is similar.. but didn't really see one.

**Comment by arallsopp** [comment]
Howdo @bryeartem. Neither of those URLs is accessible from the UK. Not sure if there's another link you can share, or a screen capture? Is it a hue fixture?

**Comment by bryeartem** [comment]
![4C7E5339-1E83-4078-A432-E26E762BA3E1](https://user-images.githubusercontent.com/45539718/155756221-2d19e53e-1505-4e24-9815-c4fcfd5755f2.jpeg)
![D1355142-AB20-4E54-A34D-4691C0C03ADF](https://user-images.githubusercontent.com/45539718/155756224-03894057-3765-45c7-841c-adae22d49ce3.jpeg)

**Comment by arallsopp** [comment]
Thanks for sourcing the pictures. This library is really about "Hue" lamps and fixtures, and neither of those appears to be a hue appliance.

Whilst I can't fix this here, there are a few of these requests coming through now, so it might be that I can spin up a new repo to track additional icons. I'm closing for now, but may come back to this.

Andy.
