### ISSUE TITLE
Icon Request bulb-group-classic* 3 and 4 bulbs

### ISSUE THREAD

**Issue by nagyrobi** [arallsopp/hass-hue-icons#129]
**What is the specific model of hue fixture/bulb that you want an icon for**

`bulb-group-classic` and `bulb-group-classic-hung` are great for generic fixtures containing multiple bulbs.
We have fixtures containing 5 and 8 bulbs, but these are wired and connected to switches in a way that the user can choose if they want groups 2, 3, or 4 bulbs to be lit on at once, thus the icon representing the switch in HA and openHASP would be nice if could show these options by the number of bulbs in the icon.

I see that icons with 3 and 4 light source groups are already present for other models, my request is to have from the `classic` and `classic-hung` bulb also 3 and 4-bulbs versions.

Thank you.

**Comment by arallsopp** [comment]
Note to self: Update the font file after doing this, else openHASP won't show the new ones.

**Comment by arallsopp** [comment]
Right. The 3 bulb versions are staged for release.

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-classic-3](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-3.svg)| hue:bulb-group-classic-3|
| ![hue:bulb-group-classic-hung-3](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-hung-3.svg)| hue:bulb-group-classic-hung-3|

The fours are going to be a bit tighter on space. Let's see.

**Comment by arallsopp** [comment]
Well, its a bit mucky at the moment, but it'll come good, I think 
![image](https://user-images.githubusercontent.com/2462104/152041470-f18eaa65-9131-4b44-bbd8-6c3c1dfe462f.png)

**Comment by arallsopp** [comment]
Getting closer...
![image](https://user-images.githubusercontent.com/2462104/152042308-ff97093d-8108-4c28-b60b-fbdea80830f6.png)

**Comment by nagyrobi** [comment]
You could perhaps increase a tiny bit the distance between the two side bulbs. That way the one at the back could get more presence.

**Comment by nagyrobi** [comment]
No problem is the aspect ratio gets wider, you could eventually decrease the overall height then to keep it within the boundaries.

**Comment by arallsopp** [comment]
I'll run this one, and see how we go. When the back bulb drops too far, it starts looking like a tail (or worse) :)

**Comment by nagyrobi** [comment]
Initially I thought you'd just line up the 3 or the 4 just like the 2 are...

**Comment by nagyrobi** [comment]
I reduced the size to see it as a small icon... look a bit tight to me.

**Comment by arallsopp** [comment]
Does this work better?

![image](https://user-images.githubusercontent.com/2462104/152044029-11646065-5e31-444e-8103-c97ccaac727b.png)

**Comment by nagyrobi** [comment]
> Does this work better?
> 
> ![image](https://user-images.githubusercontent.com/2462104/152044029-11646065-5e31-444e-8103-c97ccaac727b.png)

Wow. A lot better.

**Comment by nagyrobi** [comment]
You could keep both versions, in 3 and 4 as _standard_ and _alt_.
If not, I vote for the one with bulbs in a row.

**Comment by nagyrobi** [comment]
> Otherwise we are probably into numerals

Noooo.

**Comment by arallsopp** [comment]
Ok, @nagyrobi. Thanks for the pointers. Here's what's coming:

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-classic-3](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-3.svg)| hue:bulb-group-classic-3|
| ![hue:bulb-group-classic-hung-3](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-hung-3.svg)| hue:bulb-group-classic-hung-3|
| ![hue:bulb-group-classic-3-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-3-alt.svg)| hue:bulb-group-classic-3-alt|
| ![hue:bulb-group-classic-hung-3-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-hung-3-alt.svg)| hue:bulb-group-classic-hung-3-alt|
| ![hue:bulb-group-classic-4](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-4.svg)| hue:bulb-group-classic-4|
| ![hue:bulb-group-classic-hung-4](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-hung-4.svg)| hue:bulb-group-classic-hung-4|
| ![hue:bulb-group-classic-4-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-4-alt.svg)| hue:bulb-group-classic-4-alt|
| ![hue:bulb-group-classic-hung-4-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-hung-4-alt.svg)| hue:bulb-group-classic-hung-4-alt|

**Comment by arallsopp** [comment]
I'll probably push this release, then update the font file afterwards, as the mapping for that is on another machine.

**Comment by arallsopp** [comment]
Closing with the above now in release [v.1.2.7](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.7).

I'll update the font and ping here when I'm back on my other machine.

**Comment by nagyrobi** [comment]
Thank you. Looking forward for the font version, as actually that's the main usage of it.

**Comment by nagyrobi** [comment]
Hi!
Any chance you could update the TTF font release too?

**Comment by arallsopp** [comment]
Howdo. Yep. Let to try to get to that next.
