### ISSUE TITLE
Home Assistant Androd app error

### ISSUE THREAD

**Issue by vawaver** [arallsopp/hass-hue-icons#130]
Home Assistant 2022.2.6 - server
HA for Android v2022.1.1-full

I added Custom Mushroom Light Card to Lovelace.
When I opened Home Assistant on my Android phone I see this error message only.
![Screenshot_20220212_130831_io homeassistant companion android](https://user-images.githubusercontent.com/52236863/153720228-5002b326-833d-41b1-b412-0bdefc01fa7f.jpg)

**Comment by arallsopp** [comment]
Hello @vawaver 

Unsure how this relates to hass hue icons. 

Did you mean: https://community.home-assistant.io/t/mushroom-cards-build-a-beautiful-dashboard-easily/388590

**Comment by arallsopp** [comment]
No worries. Thanks for the update.
