### ISSUE TITLE
Icon Request [name of fixture]

### ISSUE THREAD

**Issue by acbsh11** [arallsopp/hass-hue-icons#131]
Lutron Aurora Smart Bulb Dimmer Switch

[**Provide a URL that points to an image of this fixture/bulb**]

Amazon page: https://www.amazon.com/Lutron-Aurora-Dimmer-Philips-Z3-1BRL-WH-L0/dp/B07RJ14FBS

Side view image: https://m.media-amazon.com/images/I/51TS3ClSrCL._AC_.jpg

I would like an icon that shows this round dimmer either straight on or at an angle like in the second link labeled "Side view image" above. Please do not include the plate behind the dimmer. 

Thanks so much!

**Comment by arallsopp** [comment]
Sounds good. Will go for the side angle.

**Comment by acbsh11** [comment]
> Sounds good. Will go for the side angle.

Thanks so much!

**Comment by arallsopp** [comment]
<img width="367" alt="image" src="https://user-images.githubusercontent.com/2462104/153721635-2c96a234-891d-4da2-b5ff-ba9fefbc7e2c.png">

That's looking pretty good. This the kind of thing you want, @acbsh11 ?

**Comment by acbsh11** [comment]
Yes! Is there any way the front circular face could be filled in? Maybe with a smaller circle? Thanks so much!

**Comment by arallsopp** [comment]
A: <img width="372" alt="image" src="https://user-images.githubusercontent.com/2462104/153721691-e441f81a-16b0-4e13-9c3a-d6cca6ac25af.png">

B:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/2462104/153721729-c6f3855b-c716-4d61-ac87-5f85773686ec.png">

I'm thinking B.

**Comment by acbsh11** [comment]
I think I like A better. I like to change the colors of the icons I use based on state. Is there any way to remove the back piece on the right? I think in the picture, that darker spot is just a reflection. Thanks so much!

**Comment by arallsopp** [comment]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/2462104/153722574-cb6f300b-014f-4758-95a7-83ba8017ab6b.png">
Like this?

**Comment by acbsh11** [comment]
Yes! Thanks!

**Comment by arallsopp** [comment]
Ok. Have gone out as threatened, but will map it into the next release when I get back. Might add an alt version in there too :)

**Comment by arallsopp** [comment]
Closing now, as actioned. Cheers again for the suggestion.
