### ISSUE TITLE
Icon request: Home

### ISSUE THREAD

**Issue by lassir** [arallsopp/hass-hue-icons#132]
**What is the specific model of hue fixture/bulb that you want an icon for**

Home icon from the Hue app

**Provide a URL that points to an image of this fixture/bulb**

![tabbarHome](https://user-images.githubusercontent.com/2715395/155591540-ea3cc3bc-c097-4d01-af7b-f5b44d95163b.svg)

![2022-02-24 21 12 15](https://user-images.githubusercontent.com/2715395/155591423-43a74104-3b42-4285-a6b6-9012e73b96d3.jpg)

**Additional context**

The icon is included in the [official icon pack](https://developers.meethue.com/develop/application-design-guidance/icon-pack/#Download).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg width="32px" height="32px" viewBox="0 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 51.3 (57544) - http://www.bohemiancoding.com/sketch -->
    <title>tabbarHome</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g fill="#101010">
            <path d="M27.6631,14.191252 L16.7081,4.27825203 C16.3091,3.90825203 15.6921,3.90725203 15.2921,4.27525203 L4.3401,14.188252 C3.6391,14.832252 4.0951,16.000252 5.0471,16.000252 L6.9891,16.000252 L6.9761,27.000252 C6.9761,27.552252 7.4241,28.000252 7.9761,28.000252 L16.9871,28.000252 L16.9871,22.000252 C16.9871,21.447252 17.4351,21.000252 17.9881,21.000252 L19.9901,21.000252 C20.5441,21.000252 20.9921,21.447252 20.9921,22.000252 L20.9921,28.000252 L21.0061,28.000252 L23.9851,28.000252 C24.5381,28.000252 24.9861,27.552252 24.9861,27.000252 L25.0001,16.000252 L26.9531,16.000252 C27.9031,16.000252 28.3601,14.836252 27.6631,14.191252"></path>
        </g>
    </g>
</svg>
```

**Comment by arallsopp** [comment]
Thanks for including that reference. This makes it much easier!

**Comment by arallsopp** [comment]
Thanks for the spot, @lassir. Its in release [v.1.2.9](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.9).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 220 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
