### ISSUE TITLE
Flip the 3 and 4-bulbs icons horizontally

### ISSUE THREAD

**Issue by nagyrobi** [arallsopp/hass-hue-icons#133]
Thank you for the 3 and 4-bulb icons. Their final usage in OpenHASP:

![kép](https://user-images.githubusercontent.com/1550668/156928961-b0222b31-ba6c-4bfa-8f72-880cfcee5877.png)

I just didn't notice that they are flipped compared to the original 2-bulbs version...

**Comment by arallsopp** [comment]
We already have hung variants, so I think what you are asking for is to have the larger bulb on the other side?

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-classic-3](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-3.svg)| hue:bulb-group-classic-3|
| ![hue:bulb-group-classic-hung-3](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-hung-3.svg)| hue:bulb-group-classic-hung-3|
| ![hue:bulb-group-classic-4](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-4.svg)| hue:bulb-group-classic-4|
| ![hue:bulb-group-classic-hung-4](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-hung-4.svg)| hue:bulb-group-classic-hung-4|

**Comment by nagyrobi** [comment]
Yes, it's that the "original" 2-bulbs version has bulb sizes _increasing_ from left to right. The 3 and 4 versions have bulb sizes _decreasing_ from left to right...

By flip I meant not rotating by 180degrees, but mirror on a vertical axis.

**Comment by arallsopp** [comment]
Thanks @nagyrobi. Its in release [v.1.2.11](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.11). 

I've updated the iconfont at the same time, so that you can use this in OpenHASP.

Cheers again, and apologies for the delay.

**Comment by nagyrobi** [comment]
great! thank you:
![kép](https://user-images.githubusercontent.com/1550668/161935153-96336b31-f639-41c9-b89c-0424a27255fa.png)
