### ISSUE TITLE
Icon Request Heated Towel Rail

### ISSUE THREAD

**Issue by david-holbrook** [arallsopp/hass-hue-icons#134]
Heated Towel Rail (plugged into Hue Smart Plug)

https://www.sinkwarehouse.com.au/products/non-heated-towel-rail-round-5-bar-750x550mm.html 

Image: https://cdn11.bigcommerce.com/s-e8hbhudqv3/images/stencil/608x608/products/2440/10693/apinrxwpw__25857.1630882669.jpg?c=2 

I would love an icon that shows a basic towel rail like the one linked above that I'm running off my Hue Smart Plug. I know it's not a Philips product - but it would be fantastic to have an icon for my HA dashboard that matched the style of all your other great icons.

Thanks for all your great work on this!

**Comment by arallsopp** [comment]
I get you, @david-holbrook. As you've noted, this library is really about "Hue" lamps and fixtures so I can't really fix this here.

That said, there are a few of these requests coming through now, so it might be that I can spin up a new repo to track additional icons. I'm closing for now, but may come back to this.

Thanks again,

Andy.
