### ISSUE TITLE
EXT: IKEA Death Star lamp

### ISSUE THREAD

**Issue by nagyrobi** [arallsopp/hass-hue-icons#135]
This is a tough one 🤣 

**What is the specific model of hue fixture/bulb that you want an icon for**

IKEA Death Star lamp

**Provide a URL that points to an image of this fixture/bulb**

https://www.ikea.com/us/en/p/ikea-ps-2014-pendant-lamp-white-silver-color-00311498/

https://www.ikea.com/us/en/images/products/ikea-ps-2014-pendant-lamp-white-silver-color__0880374_pe548623_s5.jpg?f=xl

**Additional context**

Something like this:
https://pixl.varagesale.com/http://s3.amazonaws.com/hopshop-image-store-production/146742845/9bc8323b97f02b6dc3c06bdd5491f899.jpg?_ver=large_uploader_thumbnail&w=640&h=640&fit=crop&s=188caabd4a1bd61db3ad462e0d102b37

I think it's enough to just have the body of the lamp, de icon doesn't have to contain the ceiling mount and the cable, and the pulling handles underneath. Just the globe in closed state.

**Comment by arallsopp** [comment]
Oh, I know that light. Hard to argue it belongs in a HUE repo though. 

I may stand up a new repo that models a few of the oddball requests that come through when time affords it.

**Comment by nagyrobi** [comment]
Yeah I know it's not HUE-specific indeed.

**Comment by arallsopp** [comment]
Cripes. Its not an easy one, for sure :)

<img width="758" alt="image" src="https://user-images.githubusercontent.com/2462104/161942566-0104955f-f41a-4da5-952d-6608b64ed37d.png">

I'll attach this as an svg here, and if I get the chance to write a library to use it, will create a new repo for that. Until then, I think maybe look up https://github.com/thomasloven/hass-fontawesome as that lets you load custom svgs.

**Comment by arallsopp** [comment]
Here you go:
![ikea death star](https://user-images.githubusercontent.com/2462104/161944254-4806b652-6efe-446f-828c-15abe9964a4b.svg)

**Comment by nagyrobi** [comment]
Cool thanks. I'm using the TTF font version...

**Comment by arallsopp** [comment]
Am closing for now as a non Hue issue. I'm looking to collate the requests for non Hue icons, and move them into a new repo, so will post back here if I transfer this one in.
