### ISSUE TITLE
Icon Request [iris group]

### ISSUE THREAD

**Issue by Rodger13Dodger** [arallsopp/hass-hue-icons#136]
_I love too see a group of two of the already present Iris as I have two lamps on my rear speakers behind the couch.

Nothing fancy, just the available hue:iris shifted with two lights.

**Comment by arallsopp** [comment]
OK. Will jump on that tonight.

**Comment by arallsopp** [comment]
Its quite hard to get them to present without confusion. 

I think I'm going for the below
:  
<img width="314" alt="image" src="https://user-images.githubusercontent.com/2462104/162632163-f1ab31ec-94a8-4157-a636-df9549a8c5f2.png">

**Comment by arallsopp** [comment]
Yeah, that looks ok to me. Let me know if you prefer something else.

| Icon | Name |
| :--- | :--- |
| ![hue:iris-group](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/iris-group.svg)| hue:iris-group|

The current version is in release [v.1.2.12](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.12).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 222 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by Rodger13Dodger** [comment]
Looks great, thank you for the more than quick solution.
