### ISSUE TITLE
Icon Request [name of fixture]

### ISSUE THREAD

**Issue by GunterAv** [arallsopp/hass-hue-icons#137]
Hello,

can you add following image?
![New](https://user-images.githubusercontent.com/87611027/163336176-6e89f77c-cdaa-4cbc-a6c4-09be97426188.PNG)

![20220414_093523_resized](https://user-images.githubusercontent.com/87611027/163336936-41c26941-2dca-4054-a4ab-c1bf4df5a3a8.jpg)

like: hue:amarant

and please a lamp like this:
![20220414_093401_resized](https://user-images.githubusercontent.com/87611027/163337021-618486d8-5dd8-4a38-ad58-f67a19a4b131.jpg)

Thanks and best regards
Gunter

Sorry for my bad English, my homelanguage are German ;-)

**Comment by Cafun** [comment]
Oh +1 for the first picture :-)

**Comment by arallsopp** [comment]
Thanks @GunterAv (and @Cafun).

This library is really about "Hue" lamps and fixtures, and neither of those appears to be a hue appliance. 

Whilst I can't fix this here, there are a few of these requests coming through now, so it might be that I can spin up a new repo to track additional icons. I'm closing for now, but may come back to this.

Andy.

**Comment by GunterAv** [comment]
Hello,

Thank you for your answer.
It would be nice if there would be an additional icon pack.

best regards
Gunter

**Comment by arallsopp** [comment]
Hey @GunterAv and @Cafun.

Just to let you know, @Mariusthvdb has started work on a [custom icon pack](https://github.com/Mariusthvdb/Custom-icons) that includes non hue icons. It may be worth creating a request or joining the discussion over there.

If I get time, I'll propose a set of icons that meet your needs.

**Comment by arallsopp** [comment]
@GunterAv: thanks for providing the reference! :)

<img width="348" alt="image" src="https://user-images.githubusercontent.com/2462104/168118334-b3619ab0-2238-4adb-9f02-f1e3f036334c.png">

**Comment by GunterAv** [comment]
Hello,

I created the icons myself and they were integrated in:
[https://github.com/elax46/custom-brand-icons](url)

* table-cylinder-lamp
* uplighter
* 2-way-uplighter

Thanks for your efforts
Gunter

**Comment by arallsopp** [comment]
Oh, ok. Well, the pull request is into marius' repo. 

Heads up, that repo has been stealing icons and not providing any accreditation to the original author. I know because they've stolen over 300 of mine. It got flagged by the community and the code owner briefly added a reference back to this repo, but they pulled it again once the fire died down.

Not great.
