### ISSUE TITLE
Icon Request [name of fixture]

### ISSUE THREAD

**Issue by jayegles** [arallsopp/hass-hue-icons#139]
Hi,

I would love to have icons for off state of hue:bulb-group-bollard-3 and hue:ceiling-buratto-two.

example: hue:floor-lantern-off

Thanks and regards

**Comment by arallsopp** [comment]
| :--- | :--- |
| ![hue:bulb-group-bollard-3-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-bollard-3-off.svg)| hue:bulb-group-bollard-3-off|

| Icon | Name |
| :--- | :--- |
| ![hue:ceiling-buratto-two-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-buratto-two-off.svg)| hue:ceiling-buratto-two-off|

I've just closed #138 so will make this into release [v.1.2.13](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.13).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 225 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
