### ISSUE TITLE
Hue Econic Outdoor light both hanging and not hanging

### ISSUE THREAD

**Issue by Maltavius** [arallsopp/hass-hue-icons#142]
**What is the specific model of hue fixture/bulb that you want an icon for**

https://www.philips-hue.com/sv-se/p/hue-white-and-color-ambiance-econic-vaggbelysning-utomhus/1743930P7
https://www.philips-hue.com/sv-se/p/hue-white-and-color-ambiance-econic-vaggbelysning-utomhus/1744030P7

**Provide a URL that points to an image of this fixture/bulb**

[]
https://www.assets.signify.com/is/image/PhilipsLighting/2ea2ba1a837f430bb72ca9cf0093aaf3?wid=960&hei=720&qlt=82
https://www.assets.signify.com/is/image/PhilipsLighting/fdddaefd427448e8bfd7a9cf009392e4?wid=960&hei=720&qlt=82

**Additional context**

**Comment by arallsopp** [comment]
Let me know if there's an alias I should add to help identify these in the future.

**Comment by Maltavius** [comment]
It was just me that didn't understand that I could write just econic to find them

**Comment by arallsopp** [comment]
Ah! Fair enough. Yes, that's a feature added into HomeAssistant by @piitaya in 2021.11. 

I leaned on them quite heavily to help me get this repo mapping correctly.
