### ISSUE TITLE
Impress narrow multiple

### ISSUE THREAD

**Issue by Schrikt** [arallsopp/hass-hue-icons#143]
Hue impress narrow

hue:wall-impress-narrow

**Additional context**

I have those lamps in sets of 2 and 3. Can you create icon with multiple impress narrow lamps? Preferable with one with 2 lamps and 1 with 3 lamps.

**Comment by arallsopp** [comment]
Will take a look.

Back soon!

**Comment by arallsopp** [comment]
Going to get quite busy to fit 3 in there. Two works quite nicely:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/2462104/165622286-47027188-3b47-4189-96af-1e287aee2b65.png">

**Comment by arallsopp** [comment]
Can just about get the three into place. Have had to make them slightly taller/narrower as they go backward, else the geometry goes out. The original isn't quite symmetrical in its vanishing point, and that becomes more obvious as you repeat and scale:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/2462104/165623371-85c04e18-68d2-495c-a4db-5c655180987b.png">

I reckon these are about as good as it'll get. If you're happy, @Schrikt, I'll bundle them into a release.

**Comment by arallsopp** [comment]
Thanks for the suggestion, @Schrikt. They'll be in release [v.1.2.15](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.15). Any changes or feedback, let me know here :)

| Icon | Name |
| :--- | :--- |
| ![hue:wall-impress-narrow-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wall-impress-narrow-two.svg)| hue:wall-impress-narrow-two|
| ![hue:wall-impress-narrow-three](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wall-impress-narrow-three.svg)| hue:wall-impress-narrow-three|


### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 231 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by Schrikt** [comment]
Thanks! Completely happy with them 👍
