### ISSUE TITLE
Hue runner spots

### ISSUE THREAD

**Issue by Schrikt** [arallsopp/hass-hue-icons#144]
Hue runner spot 1, 2 and 3 spots variants

Links to product pages:
https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-runner--enkele-spot/8719514338364

https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-runner-2-licht-spotbalk/8719514338166

https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-runner-3-lichts-spotbalk/8719514338401

**Additional context**

For these lights you get entry’s for every spot. Is it possible to create also icons to see which spot it is? So for the 2 spot variant the left or right has a different look.

**Comment by arallsopp** [comment]
I'm thinking of this for the single.

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/2462104/165953154-fb6d7f4d-4ccd-477a-acd0-434547cb2104.png">

still toying with the angled 'arm' piece, as it might be superfluous.

**Comment by Schrikt** [comment]
Looks good! Only thing that comes to mind is the possibility that this one can be mounted to a wall as well a ceiling.

**Comment by arallsopp** [comment]
These would need to be scaled down, but along these lines:
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/2462104/165956201-7e2efd5a-fc94-4278-a36e-3979bf630000.png">

Then we could knock out the white circle for the ones that are off, perhaps :)

**Comment by arallsopp** [comment]
Ok. So the 'on' variants are all in release [v.1.2.17](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.17).

| Icon | Name |
| :--- | :--- |
| ![hue:wall-runner](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wall-runner.svg)| hue:wall-runner|
| ![hue:ceiling-runner](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-runner.svg)| hue:ceiling-runner|
| ![hue:ceiling-runner-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-runner-two.svg)| hue:ceiling-runner-two|
| ![hue:ceiling-runner-three](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-runner-three.svg)| hue:ceiling-runner-three|

I'll work on the 'off' versions shortly, so that you can see which bulb is being targeted. Not sure what happened, but suddenly I've got an armful of icon requests in :)

**Comment by arallsopp** [comment]
For the featured bulb variant, how about this:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/2462104/166117508-3f587d90-aef1-4d54-b431-38c2cc9e907e.png">

I guess question is, should the centre be shaded for the bulb thats ON, or OFF.

**Comment by Schrikt** [comment]
I’m not really looking for the difference between on and off. More if I’m controlling the left, middle or right one. How does it look when 2 are completely black? Or just one with a small black round in it?

**Comment by Schrikt** [comment]
> I'll work on the 'off' versions shortly, so that you can see which bulb is being targeted. Not sure what happened, but suddenly I've got an armful of icon requests in :)

Isn’t that what you asked for in the release notes? 😉 keep up the good work. I really appreciate it!

**Comment by arallsopp** [comment]
Here's just one with a small black round in it.
<img width="430" alt="image" src="https://user-images.githubusercontent.com/2462104/166118301-1e92236f-6249-4eaf-a475-e7223c2c429e.png">

And here's two completely black. 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/2462104/166118325-8c6bc32f-2f8b-4a81-b51a-e74be9714534.png">

I think all black just loses the shape of the thing, so if we are looking to target a single bulb, I think the small round dots are a better way to highlight it.

<img width="434" alt="image" src="https://user-images.githubusercontent.com/2462104/166118360-17f40b32-e571-4ccd-85d8-16c1cdce5bee.png">

Would be just bulb 1.

**Comment by arallsopp** [comment]
Does that work for you? Its probably nicer than having two 'off' dots on the non controlling light.

**Comment by Schrikt** [comment]
I agree. I would prefer 1 dot than 2 dots.

**Comment by arallsopp** [comment]
Ok. They'll be in the next release as modelled below:

| Icon | Name |
| :--- | :--- |
| ![hue:ceiling-runner-two-bulb-one](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-runner-two-bulb-one.svg)| hue:ceiling-runner-two-bulb-one|
| ![hue:ceiling-runner-two-bulb-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-runner-two-bulb-two.svg)| hue:ceiling-runner-two-bulb-two|

| Icon | Name |
| :--- | :--- |
| ![hue:ceiling-runner-three-bulb-one](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-runner-three-bulb-one.svg)| hue:ceiling-runner-three-bulb-one|
| ![hue:ceiling-runner-three-bulb-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-runner-three-bulb-two.svg)| hue:ceiling-runner-three-bulb-two|
| ![hue:ceiling-runner-three-bulb-three](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-runner-three-bulb-three.svg)| hue:ceiling-runner-three-bulb-three|

They'll go blue once I've stripped the extra data from the svgs.

**Comment by Schrikt** [comment]
👍 tnx

**Comment by arallsopp** [comment]
Thanks again @Schrikt. They're in release [v.1.2.18](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.18).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 257 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by sarrandalls** [comment]
Heads up, the icons you've created for @Schrikt  have been stolen by elax46 again. 
https://github.com/elax46/custom-brand-icons/commit/b56d8ff47f338bee235eade62922d3fd59e24ed7

**Comment by sarrandalls** [comment]
He has bundled them into https://github.com/elax46/custom-brand-icons/releases/tag/1.0.56 and not given any credit to @arallsopp. Actually, looking at the source, he's also stripped the author tag from the svg file. That's a real pity :(
