### ISSUE TITLE
Hue adore ceiling lamp

### ISSUE THREAD

**Issue by Schrikt** [arallsopp/hass-hue-icons#145]
Hue adore ceiling lamp

https://www.philips.nl/c-p/8718696175811/hue-white-ambiance-adore-plafondlamp-voor-de-badkamer

**Comment by Schrikt** [comment]
Is it possible to reflect the space between the lamp and the ceiling? In the different ceiling (eg being and fair) lamps I have seen different angles for the lamps. That looks a little odd:
![PNG-afbeelding](https://user-images.githubusercontent.com/60716169/165910648-3cdd6b3e-e33a-4f5b-ae72-1eae3846edbd.png)
I would prefer the angle of the fair lamp (the upper one). This angle would probably give a little more options to show the space between lamp and ceiling.

**Comment by arallsopp** [comment]
alternative is to try to recreate that ring:
<img width="889" alt="image" src="https://user-images.githubusercontent.com/2462104/165910833-aba15bc9-8777-4abd-b160-b8800a9504c0.png">

I may just create both, tbh.

**Comment by arallsopp** [comment]
I've based the angle on the photo from Hue. I can make it more horizontal, but you'll lose the room for the inner ring. Also, can't see how far from the ceiling it is. Could it be as simple as adding a bar to the top surface?

Number 3 here looking pretty good to me:
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/2462104/165911539-6d9196cb-15f1-40ce-83a6-a632116b51a6.png">

**Comment by Schrikt** [comment]
Only the ring gives light (up and down). In the middle is a white plate. Besides it is white this should probably be filled in the image. There is only about 1cm between lamp and ceiling. The image on the right already implies too much distance between lamp and ceiling. Without it would be better.
![image](https://user-images.githubusercontent.com/60716169/165912048-492043aa-3705-4b18-9c57-682f466fb328.jpg)
![image](https://user-images.githubusercontent.com/60716169/165912130-7d8bb462-908f-4c5e-9cf8-9f17a4c243a2.jpg)
![image](https://user-images.githubusercontent.com/60716169/165912174-ec52cb58-869f-4267-9c62-bd143f563e6a.jpg)

**Comment by Schrikt** [comment]
Completely correct. The fair unit is directly to the ceiling. This one has about 1.5 cm between ceiling and lamp to distribute light as well

**Comment by Schrikt** [comment]
Maybe I’m a little too critical and maybe it is not possible. But I would like to have the body in image 6 a little smaller, the circle in the middle a little bigger. With the smaller body it is possibly an option to have the small top of picture 5 on it. Preferable a little wider than in picture 5. Appreciate the effort you take on this one!

**Comment by arallsopp** [comment]
LOL. So, you're up against mininum line widths for the circle in the middle, because its already only 1px white at the bottom. That said, I could make it slightly wider, maybe.

For the body, I'm guessing you mean 'shorter' so that it takes less height?

Item 7, perhaps?

<img width="927" alt="image" src="https://user-images.githubusercontent.com/2462104/165922159-8484b588-86e7-42b2-8b2c-db1c2ae952d0.png">

**Comment by Schrikt** [comment]
Yes, 7 looks best. I only have some doubt about the top (between ceiling and lamp). If it can’t be wider it is probably better to have it without. Maybe you can have 2 variants.

**Comment by Schrikt** [comment]
Yes, I love that one

**Comment by arallsopp** [comment]
Hurrah! Right. I'll bundle that into the next release as hue:adore-ceiling. 

Thanks for bearing with me :)

**Comment by arallsopp** [comment]
Thanks again, @Schrikt. Your request (ceiling-adore) will be in release [v.1.2.16](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.16), along with some of the alternates.

| Icon | Name |
| :--- | :--- |
| ![hue:ceiling-adore](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-adore.svg)| hue:ceiling-adore|
| ![hue:ceiling-adore-flush](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-adore-flush.svg)| hue:ceiling-adore-flush|
| ![hue:ceiling-adore-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-adore-alt.svg)| hue:ceiling-adore-alt|
| ![hue:ceiling-adore-alt-flush](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-adore-alt-flush.svg)| hue:ceiling-adore-alt-flush|
