### ISSUE TITLE
Room light icons

### ISSUE THREAD

**Issue by Schrikt** [arallsopp/hass-hue-icons#146]
I’m a little struggling with the difference between a hue group and a room. The hue icons have a icon for the living room (sofa). I use that icon in home assistant for the area living room (with the lamps, tv and other devices in it). But I also have a hue group living room that only contains the different lights in the living room. Every light has the icon of the hue lamp it is. I would like an icon for only the lights group that represents all lights in the living room. Don’t know a solution yet, but probably you have an idea.

**Comment by arallsopp** [comment]
The rules I'm using are:
- if the room has 3 of the same light, I use a -three variant (eg. hue:pendant-devote-three)
- if the room has two different lights, I use a bulb-group variant (eg. hue:bulb-group-candle-lightstrip)
- if the room has more than two different lights, I use an icon for the room's purpose (eg. hue:room-bedroom)

Its not a hard and fast rule, but it gets me through. I do have 'areas' within my rooms (dining table, atrium, etc) that use the same rules, mind.

**Comment by arallsopp** [comment]
Happy to close this now?
