### ISSUE TITLE
Icon Request [hue:ceiling-flush-circular group

### ISSUE THREAD

**Issue by gxc7719** [arallsopp/hass-hue-icons#147]
**What is the specific model of hue fixture/bulb that you want an icon for**

Group of Downlight 5/6 inch

**Provide a URL that points to an image of this fixture/bulb**

https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-downlight-5-6-inch/5996611U5

**Additional context**

I created a group in hue for my kitchen ceiling lights. There is an icon for the light but I didn't see one for a group of these lights.

**Comment by arallsopp** [comment]
Got you. Will get that in over the weekend if not before.

**Comment by arallsopp** [comment]
Work in progress...
<img width="533" alt="image" src="https://user-images.githubusercontent.com/2462104/166080021-dde8554f-2a24-43a4-b1a7-24556d006532.png">

**Comment by arallsopp** [comment]
It'll come, and when it does, it'll look like this:

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-ceiling-flush-circular](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-ceiling-flush-circular.svg)| hue:bulb-group-ceiling-flush-circular|

**Comment by gxc7719** [comment]
Awesome! Thanks a lot. I never expected it to be done so fast. Nice work.

**Comment by arallsopp** [comment]
Thanks again for the suggestion, @gxc7719.  Your icons are in release [v.1.2.17](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.17).

| Icon | Name |
| :--- | :--- |
| ![hue:ceiling-flush-circular](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-flush-circular.svg)| hue:ceiling-flush-circular|
| ![hue:bulb-group-ceiling-flush-circular](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-ceiling-flush-circular.svg)| hue:bulb-group-ceiling-flush-circular|


### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 240 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
