### ISSUE TITLE
Icon Request [multiple fixtures]

### ISSUE THREAD

**Issue by satyambaba** [arallsopp/hass-hue-icons#148]
**What is the specific model of hue fixture/bulb that you want an icon for**

Thanks for these awesome icons. I'm requesting following icons (these are off versions of already existing icons) -

1. ceiling-fugato-two-off
2. wall-spot-off
3. floor-spot-off
4. floor-shade-off
5. play-bar-off
6. ceiling-aurelle-circle-off
7. lily-two-off
8. double-spot-off
9. pendant-cher-off
10. pendant-round-off
11. adore-alt-off
12. ceiling-aurelle-off

Thanks in advance!

**Provide a URL that points to an image of this fixture/bulb**

**Additional context**

**Comment by arallsopp** [comment]
Cheers. Thats quite a chunk of icons. It'll take me a while to start, but once I'm rolling they'll churn out. Thanks for the suggestion. I should be able to get these across during the weekend.

**Comment by satyambaba** [comment]
> Cheers. Thats quite a chunk of icons. It'll take me a while to start, but once I'm rolling they'll churn out. Thanks for the suggestion. I should be able to get these across during the weekend.

Take your time. Thanks a lot for your efforts!

**Comment by arallsopp** [comment]
OK. They'll be arriving shortly as part of release [v.1.2.18](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.18).


| No. | Icon | Name |
| :--- | :--- | :--- |
| 1 | ![hue:ceiling-fugato-two-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-fugato-two-off.svg)| hue:ceiling-fugato-two-off|
| 2 | ![hue:wall-spot-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wall-spot-off.svg)| hue:wall-spot-off|
| 3 | ![hue:floor-spot-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/floor-spot-off.svg)| hue:floor-spot-off|
| 4 | ![hue:floor-shade-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/floor-shade-off.svg)| hue:floor-shade-off|
| 5 | ![hue:play-bar-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/play-bar-off.svg)| hue:play-bar-off|
| 6 | ![hue:ceiling-aurelle-circle-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-aurelle-circle-off.svg)| hue:ceiling-aurelle-circle-off|
| 7 | ![hue:lily-two-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lily-two-off.svg)| hue:lily-two-off|
| 8 | ![hue:double-spot-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/double-spot-off.svg)| hue:double-spot-off|
| 9 | ![hue:pendant-cher-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-cher-off.svg)| hue:pendant-cher-off|
| 10 | ![hue:pendant-round-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-round-off.svg)| hue:pendant-round-off|
| 11 | ![hue:adore-alt-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/adore-alt-off.svg)| hue:adore-alt-off|
| 12 | ![hue:ceiling-aurelle-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-aurelle-off.svg)| hue:ceiling-aurelle-off|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 257 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by arallsopp** [comment]
Released as part of [v.1.2.18](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.18).

**Comment by satyambaba** [comment]
> Released as part of [v.1.2.18](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.18).

Wow, this is amazing! Thanks a lot for your help 👍

**Comment by arallsopp** [comment]
My pleasure, and thanks for the star.
