### ISSUE TITLE
Group of plugs

### ISSUE THREAD

**Issue by wrt54g** [arallsopp/hass-hue-icons#149]
**What is the specific model of hue fixture/bulb that you want an icon for**
Smart Plug

**Provide a URL that points to an image of this fixture/bulb**
https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_86682437/fee_325_225_png

**Additional context**

I want a group icon for the Smart Plug.

**Comment by wrt54g** [comment]
This icon is great, thanks!

**Comment by arallsopp** [comment]
Cheers Sven. Thanks for letting me know.
