### ISSUE TITLE
icon off ?

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#151]
hello would you like to make this icon an off version of thanks already ?

1. centris
2. centris-two
3. centris-tree
4. flourish-alt
5. wellner-solid
6. wellness

**Comment by arallsopp** [comment]
Will give this a look tomorrow morning.

**Comment by jrspowers** [comment]
that would be very nice thanks already !

**Comment by arallsopp** [comment]
Thanks for waiting, @jrspowers. These will be in release [v.1.2.19](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.19).

| No | Icon | Name |
| :--- | :--- | :--- |
| 1 | ![hue:centris-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/centris-off.svg)| hue:centris-off|
| 2 | ![hue:centris-two-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/centris-two-off.svg)| hue:centris-two-off|
| 3 | ![hue:centris-three-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/centris-three-off.svg)| hue:centris-three-off|
| 4 | ![hue:flourish-alt-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/flourish-alt-off.svg)| hue:flourish-alt-off|
| 5 | ![hue:wellner-solid-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wellner-solid-off.svg)| hue:wellner-solid-off|
| 6 | ![hue:wellness-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wellness-off.svg)| hue:wellness-off|

**Comment by jrspowers** [comment]
Thanks man 🙂
