### ISSUE TITLE
Room off icons

### ISSUE THREAD

**Issue by IgneaX** [arallsopp/hass-hue-icons#152]
Hello, 

At first i want to say thanks for your great work! 👍🏻
is it possible to create off variants for the room icons, like room-bedroom, room-laundry, room-living?

**Comment by arallsopp** [comment]
yes, I can do that. Is it every room icon you want? I think there's like 38 of them, so it'll take a bit of time. If there's some you're using right now, let me know and I'll try to get to them first.

**Comment by arallsopp** [comment]
Here's a whole chunk of them coming for the next release:

| Icon | Name |
| :--- | :--- |
| ![hue:room-toilet-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-toilet-off.svg)| hue:room-toilet-off|
| ![hue:room-pool-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-pool-off.svg)| hue:room-pool-off|
| ![hue:room-porch-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-porch-off.svg)| hue:room-porch-off|
| ![hue:room-lounge-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-lounge-off.svg)| hue:room-lounge-off|
| ![hue:room-living-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-living-off.svg)| hue:room-living-off|
| ![hue:room-office-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-office-off.svg)| hue:room-office-off|
| ![hue:room-other-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-other-off.svg)| hue:room-other-off|
| ![hue:room-nursery-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-nursery-off.svg)| hue:room-nursery-off|
| ![hue:room-outdoors-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-outdoors-off.svg)| hue:room-outdoors-off|
| ![hue:room-storage-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-storage-off.svg)| hue:room-storage-off|
| ![hue:room-recreation-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-recreation-off.svg)| hue:room-recreation-off|
| ![hue:room-studio-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-studio-off.svg)| hue:room-studio-off|
| ![hue:room-terrace-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-terrace-off.svg)| hue:room-terrace-off|
| ![hue:room-laundry-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-laundry-off.svg)| hue:room-laundry-off|
| ![hue:room-stairs-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-stairs-off.svg)| hue:room-stairs-off|
| ![hue:room-hallway-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-hallway-off.svg)| hue:room-hallway-off|
| ![hue:room-gym-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-gym-off.svg)| hue:room-gym-off|
| ![hue:room-guestroom-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-guestroom-off.svg)| hue:room-guestroom-off|
| ![hue:room-garage-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-garage-off.svg)| hue:room-garage-off|
| ![hue:room-games-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-games-off.svg)| hue:room-games-off|
| ![hue:room-front-door-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-front-door-off.svg)| hue:room-front-door-off|
| ![hue:room-driveway-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-driveway-off.svg)| hue:room-driveway-off|
| ![hue:room-bedroom-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-bedroom-off.svg)| hue:room-bedroom-off|
| ![hue:room-dining-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-dining-off.svg)| hue:room-dining-off|
| ![hue:room-computer-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-computer-off.svg)| hue:room-computer-off|
| ![hue:room-closet-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-closet-off.svg)| hue:room-closet-off|
| ![hue:room-carport-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-carport-off.svg)| hue:room-carport-off|
| ![hue:room-kitchen-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-kitchen-off.svg)| hue:room-kitchen-off|
| ![hue:room-bbq-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-bbq-off.svg)| hue:room-bbq-off|
| ![hue:room-bathroom-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-bathroom-off.svg)| hue:room-bathroom-off|
| ![hue:room-balcony-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-balcony-off.svg)| hue:room-balcony-off|
| ![hue:room-attic-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-attic-off.svg)| hue:room-attic-off|
| ![hue:room-attic-alt-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-attic-alt-off.svg)| hue:room-attic-alt-off|
| ![hue:room-kids-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/room-kids-off.svg)| hue:room-kids-off|

The only one really annoying me is garage-off, as the prohibiting slash almost exactly follows the path of the wrench. Not sure its worth reworking the original icon to avoid it, mind, as that's the one used in the Hue app.

**Comment by arallsopp** [comment]
Thanks for the suggestion @IgneaX. The off state rooms have been added to release [v.1.2.20](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.20).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 299 custom icons has been driven by a community request just like yours, and stars help people find this repo. 

### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
