### ISSUE TITLE
icon off ?

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#153]
hello would you like to make this icon an off version of thanks already ?

1. ceiling-rect
2. room-bedroom
3. room-bathroom
4. room-games
5. room-laundry
6. room-guestroom
7. room-office

**Comment by jrspowers** [comment]
I see that you have already made the cream in the off version merci for that !

**Comment by arallsopp** [comment]
Howdo.

From the [main page](https://github.com/arallsopp/hass-hue-icons) there should be a set of buttons towards the top right of the screen (on desktop, at least) saying 'watch', 'fork' and 'star'. If you click 'star', it'll update to say 'starred' and people will be better able to find this repo :)

![image](https://user-images.githubusercontent.com/2462104/166723888-b181d137-08d0-47d5-8366-a7ae6232e81c.png)

**Comment by jrspowers** [comment]
i have you github star
