### ISSUE TITLE
Icon Request: Hue Sync/Entertainment Area

### ISSUE THREAD

**Issue by gvssr** [arallsopp/hass-hue-icons#154]
**What is the specific model of hue fixture/bulb that you want an icon for**

The icon for Entertainment areas in the Hue app, or the Sync tab and accompanying button

**Provide a URL that points to an image of this fixture/bulb**

You can see it at the top of the [Hue Sync app icon](https://play-lh.googleusercontent.com/WGr91wXKXO70SO5BxJbjB2JekHobprOAMN5yPQiVE_EQxNOKN72o254dElUZtmEsSs0=s180-rw)

**Additional context**

Some additional screenshots from my device, outlined in red:
![image](https://user-images.githubusercontent.com/61377476/166883417-4069c43c-eae7-48da-b46b-e1a1bd8cc7e5.png)
![image](https://user-images.githubusercontent.com/61377476/166883483-eb02aad9-fbb3-43b0-9aa5-b2b395645e02.png)

**Comment by arallsopp** [comment]
Good spot! Am on it.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/2462104/166887014-703b8c76-572c-4c55-b0cd-7249aab4b311.png">

**Comment by arallsopp** [comment]
Thanks for the suggestion @gvssr. It'll look like this in the next release and up at some point in the next hour.

| Icon | Name |
| :--- | :--- |
| ![hue:entertainment-area](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/entertainment-area.svg)| hue:entertainment-area|

Let me know if this works for you, Gabriel.

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 300 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by gvssr** [comment]
@arallsopp Looks great! Incredibly fast work, thank you

**Comment by arallsopp** [comment]
Thank you for the suggestion.

Release [v.1.2.21](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.21) has your request. :)
