### ISSUE TITLE
New off variants

### ISSUE THREAD

**Issue by IgneaX** [arallsopp/hass-hue-icons#156]
Hi,

you are the reason why I'm working now with Icons by states😄 Can you please add off-variants for hue:bulb-filament, hue:bulb-filament-hung, hue:bulb-classic-hung, hue:bulb-candle hue:bulb-candle-hung and hue:play-bar-v?

best regards

**Comment by arallsopp** [comment]
You tricked me with that bulb-candle-hung. It doesn't exist in an on state, so far as I can see?

**Comment by arallsopp** [comment]
Thanks for the suggestion, @IgneaX.

Off versions as below:

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-filament-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-filament-off.svg)| hue:bulb-filament-off|
| ![hue:bulb-filament-hung-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-filament-hung-off.svg)| hue:bulb-filament-hung-off|
| ![hue:bulb-classic-hung-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-classic-hung-off.svg)| hue:bulb-classic-hung-off|
| ![hue:bulb-candle-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-candle-off.svg)| hue:bulb-candle-off|
| ![hue:bulb-candle-hung-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-candle-hung-off.svg)| hue:bulb-candle-hung-off|
| ![hue:play-bar-v-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/play-bar-v-off.svg)| hue:play-bar-v-off|

and new icon:

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-candle-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-candle-hung.svg)| hue:bulb-candle-hung|

These will be in release [v.1.2.22](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.22).
### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 307 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by IgneaX** [comment]
Maybe i forget to describe, sorry for that mistake😅Am 06.05.22, 15:24 schrieb Andy Allsopp ***@***.***>:

   
  You tricked me with that bulb-candle-hung. It doesn't exist in an on state, so far as I can see?
