### ISSUE TITLE
Plug-off and plug-eu-off

### ISSUE THREAD

**Issue by wrt54g** [arallsopp/hass-hue-icons#157]
**What is the specific model of hue fixture/bulb that you want an icon for**
Plug EU

**Provide a URL that points to an image of this fixture/bulb**
https://www.beaumotica.nl/media/catalog/product/cache/3/image/16bbee25c23a77be9bd542651460046c/p/h/philips-hue-8719514342309-20281299_50.jpg

**Additional context**
I want the icons for plug off and plug EU off.

**Comment by arallsopp** [comment]
Thanks for these, and for the box art picture. That's a much better image than I had used previously. If you don't mind, I'm going to try reworking the plug-eu first, then make an off version once I'm happy with it.

**Comment by arallsopp** [comment]
Reworked plug-eu (retained old one as plug-eu-alt), and then added group and off states. This brings it inline with plug UK and plug US

| Icon | Name |
| :--- | :--- |
| ![hue:plug-eu](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-eu.svg)| hue:plug-eu|
| ![hue:plug-eu-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-eu-off.svg)| hue:plug-eu-off|
| ![hue:plug-eu-group](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-eu-group.svg)| hue:plug-eu-group|
| ![hue:plug-eu-group-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-eu-group-off.svg)| hue:plug-eu-group-off|
| ![hue:plug-uk](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-uk.svg)| hue:plug-uk|
| ![hue:plug-us](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-us.svg)| hue:plug-us|

These will be in release [v.1.2.24](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.24).

**Comment by wrt54g** [comment]
> Reworked plug-eu (retained old one as plug-eu-alt), and then added group and off states. This brings it inline with plug UK and plug US
> 
> Icon	Name
> ![hue:plug-eu](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-eu.svg)	hue:plug-eu
> ![hue:plug-eu-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-eu-off.svg)	hue:plug-eu-off
> ![hue:plug-eu-group](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-eu-group.svg)	hue:plug-eu-group
> ![hue:plug-eu-group-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-eu-group-off.svg)	hue:plug-eu-group-off
> ![hue:plug-uk](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-uk.svg)	hue:plug-uk
> ![hue:plug-us](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-us.svg)	hue:plug-us
> The old version of plug-eu is now plug-eu-alt:
> 
> Icon	Name
> ![hue:plug-eu-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/plug-eu-alt.svg)	hue:plug-eu-alt
> These will be in release [v.1.2.24](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.24).

These new icons are great, thanks!

**Comment by arallsopp** [comment]
Sorry for the delays. Glad you're happy!
