### ISSUE TITLE
icon hue sync box 

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#158]
hello can you create this icon for use with the hue sync box ?

1. Music
![muziek syncbox](https://user-images.githubusercontent.com/60328474/167181188-2375f8bf-40e3-4f85-bb8e-30f1bee81dea.jpg)
2. Subtle
![subtle syncbox](https://user-images.githubusercontent.com/60328474/167181699-3058c8f9-74d1-4f3b-9b62-bad0ac6ef4c0.jpg)
3. Moderate
![Moderate syncbox](https://user-images.githubusercontent.com/60328474/167181772-ab5567ba-d7ba-4442-b70e-c194b144eb12.jpg)
4. High
![High syncbox](https://user-images.githubusercontent.com/60328474/167181832-b9097ae1-759c-4432-a0df-0d18f675e675.jpg)
5. Intense
![Intense syncbox](https://user-images.githubusercontent.com/60328474/167181885-4c0263f9-9fda-4ad7-bf6a-4c0386198e2e.jpg)

**Comment by arallsopp** [comment]
yeah, I can try for those.

**Comment by arallsopp** [comment]
Complex one first...
<img width="643" alt="image" src="https://user-images.githubusercontent.com/2462104/167221129-2b20df38-0edf-4999-ae49-1f34f39e338c.png">

**Comment by jrspowers** [comment]
thanks man would be very nice and that looks nice wall then i can use that for my hue sync media player card

**Comment by arallsopp** [comment]
Excellent. The others are at least simpler. I'm making the line larger within the square, to help tell them apart.
<img width="757" alt="image" src="https://user-images.githubusercontent.com/2462104/167222449-13536436-a6e7-456b-9896-bfad90d5eb99.png">

**Comment by jrspowers** [comment]
that's very good looks really good nicely made and handy as bigger

**Comment by arallsopp** [comment]
I'm wondering a little if I should have put the headphones (music) into a box, also. Any thoughts on that?

| Icon | Name |
| :--- | :--- |
| ![hue:sync-music](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/sync-music.svg)| hue:sync-music|
| ![hue:sync-subtle](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/sync-subtle.svg)| hue:sync-subtle|
| ![hue:sync-moderate](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/sync-moderate.svg)| hue:sync-moderate|
| ![hue:sync-intense](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/sync-intense.svg)| hue:sync-intense|
| ![hue:sync-high](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/sync-high.svg)| hue:sync-high|

As these stand, they'll make their way to the next release.

**Comment by jrspowers** [comment]
it seems so good with the headphones I think it will come out nicely and looking forward to the next release 😊

**Comment by arallsopp** [comment]
Added the alt version anyway, just incase :)

| Icon | Name |
| :--- | :--- |
| ![hue:sync-music-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/sync-music-alt.svg)| hue:sync-music-alt|

**Comment by arallsopp** [comment]
Thanks again. 

These are now published in release [v.1.2.23](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.23).

**Comment by jrspowers** [comment]
that's very good thanks & nice going to check it out right away

**Comment by arallsopp** [comment]
If you get it working in a way you like, would you consider sharing a screenshot on the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)? I'm always looking for ways to improve my own HA install, and I've not yet really explored the sync options.

**Comment by jrspowers** [comment]
yes is good will share it for sure if i got the work how i want and do you mean the sync between hue sync box and ha or else ?

**Comment by arallsopp** [comment]
Thanks. Appreciate that. I just meant controlling the sync box from HA, really. I'd not considered doing it before, and am  intrigued to see how you lay it out and what options that might present for me. 

Sync in this house is normally just a laptop with a mic open, playing Duel of the Fates, in a darkened living room, with my kids swinging lightsabers at each other :)

**Comment by jrspowers** [comment]
yes that's true but I've been using sync box for a long time and also linked to ha and it works really nicely but now I want to make something beautiful that is handy to operate so now just find out how and so & I would like to share it  hear 😊
