### ISSUE TITLE
please add an air conditioner icon

### ISSUE THREAD

**Issue by Dilkins85** [arallsopp/hass-hue-icons#16]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Be as specific as you can, as Philips often seem to have product family names where multiple variants exist under the same description.

**Provide a URL that points to an image of this fixture/bulb**

Preferably Philips' photography, as they use a consistent angle.

**Additional context**

please add an air conditioner icon

**Comment by arallsopp** [comment]
I am unaware of a Philips hue air conditioner, and fear that icon might not belong in this set. You may find an existing mdi icon works better for you. 

mdi:air-conditioner already works in home assistant, and gives you the below. 

![image](https://user-images.githubusercontent.com/2462104/126779597-21e2ebba-b4db-42f0-9b2d-f80afe13c890.jpeg)

Does that help?

**Comment by arallsopp** [comment]
Closing this as inactive.
