### ISSUE TITLE
Aura off and aura group off.

### ISSUE THREAD

**Issue by wrt54g** [arallsopp/hass-hue-icons#161]
**What is the specific model of hue fixture/bulb that you want an icon for**
Hue Aura

**Provide a URL that points to an image of this fixture/bulb**
https://m.media-amazon.com/images/I/71Vl-UXvNdL._AC_SL1500_.jpg

**Additional context**
I want off and group off icons for the Hue Aura.

**Comment by arallsopp** [comment]
Slightly tricky these two, as the lamps are very much aligned to the off strike. I've kept the standard (slash goes from top left to bottom right) but slightly lengthened it.

| Icon | Name |
| :--- | :--- |
| ![hue:aura-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/aura-off.svg)| hue:aura-off|
| ![hue:aura-group-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/aura-group-off.svg)| hue:aura-group-off|

They'll both be in release [v.1.2.25](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.25).
