### ISSUE TITLE
Amaze off

### ISSUE THREAD

**Issue by wrt54g** [arallsopp/hass-hue-icons#162]
**What is the specific model of hue fixture/bulb that you want an icon for**
Hue Amaze

**Provide a URL that points to an image of this fixture/bulb**
https://www.beaumotica.nl/media/catalog/product/cache/3/image/16bbee25c23a77be9bd542651460046c/p/h/philips-hue-amaze-8719514341074-20283902_50.jpg

**Additional context**
I want an amaze off icon.

**Comment by arallsopp** [comment]
Not sure which flavour you wanted, so here's both. Its easier if you give me the icon name from the existing set, as I can rework it for an 'off strike through' relatively quickly if I can identify it.

| Icon | Name |
| :--- | :--- |
| ![hue:amaze-alt-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/amaze-alt-off.svg)| hue:amaze-alt-off|
| ![hue:amaze-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/amaze-off.svg)| hue:amaze-off|

This will make its way to release [v.1.2.25](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.25).
