### ISSUE TITLE
Hue Go Group off.

### ISSUE THREAD

**Issue by wrt54g** [arallsopp/hass-hue-icons#165]
**What is the specific model of hue fixture/bulb that you want an icon for**
Go Group

**Provide a URL that points to an image of this fixture/bulb**
https://www.assets.signify.com/is/image/PhilipsLighting/5dd647214c064701bff9aa140090fbdb

**Additional context**

I an off icon for the Hue Go Group.

**Existing icon name**
go-group

**Comment by arallsopp** [comment]
Added in release [v.1.2.28](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.28).
| Icon | Name |
| :--- | :--- |
| ![hue:go-group-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/go-group-off.svg)| hue:go-group-off|
