### ISSUE TITLE
Hue Devere icon

### ISSUE THREAD

**Issue by RayRent** [arallsopp/hass-hue-icons#168]
**What is the specific model of hue fixture/bulb that you want an icon for**

Philips Hue Devere ceiling model

**Provide a URL that points to an image of this fixture/bulb**

https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-devere-middelgrote-plafondlamp/4116531P6

**Additional context**

**Comment by arallsopp** [comment]
Thanks for this. 

I've just pushed a release so won't jump on this immediately if that's ok?

I'm wondering if any of the existing ceiling lamps will work for this? If not, I'm sure I can mod something for you.

**Comment by arallsopp** [comment]
It might be that I can just cover this off with an alias against one of the existing icons. Anyway, glad you have something to use in the interim.

**Comment by arallsopp** [comment]
I've reviewed the following:

| Icon | Name | 
| :--- | :--- | 
| ![hue:ceiling-round](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/ceiling-round.svg)| hue:ceiling-round |
| ![hue:recessed-ceiling](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/recessed-ceiling.svg)| hue:recessed-ceiling |
| ![hue:ceiling-adore-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-adore-alt.svg)| hue:ceiling-adore-alt |
| ![hue:ceiling-adore-alt-flush](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-adore-alt-flush.svg)| hue:ceiling-adore-alt-flush |

But I think this one merits a new icon. It'll be similar to the ceiling-round, but with a slightly thinner line weight to bring it inline with the other specific fixtures

**Comment by arallsopp** [comment]
It will look like this. Well done for spotting a lamp I didn't have! Been a while since we saw a new fixture.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/2462104/167843899-57aaaba4-e2ff-427e-be62-586e5babcba0.png">

**Comment by arallsopp** [comment]
Thanks for the suggestion @RayRent, 

hue:ceiling-devere is in release [v.1.2.28](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.28).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 350 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
