### ISSUE TITLE
Hue Milliskin icon

### ISSUE THREAD

**Issue by RayRent** [arallsopp/hass-hue-icons#169]
**What is the specific model of hue fixture/bulb that you want an icon for**

Hue Milliskin ceiling spot

**Provide a URL that points to an image of this fixture/bulb**

https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-milliskin--extra-inbouwspot/8719514338562

**Additional context**

Would be nice if this is possible

**Comment by arallsopp** [comment]
Got you. 

Think this is the same body as the centura-round. 

![image](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/centura-round.svg)

What do you reckon? Alias it, or create something new?

**Comment by RayRent** [comment]
Sorry, missed that one. The Centura-round is similar. Thanks!

**Comment by arallsopp** [comment]
No problem. I only remembered it because I drew it! :)

I'll put an alias against the name so that the picker shows it under its other name. 

Probably the only difference is one is RGB and the other is white ambiance, etc.

**Comment by RayRent** [comment]
:-)
OK, that difference shouldn't matter

**Comment by RayRent** [comment]
Great job, thx

**Comment by arallsopp** [comment]
You're welcome. Thanks for the star!
