### ISSUE TITLE
Non Hue icons? HomePod

### ISSUE THREAD

**Issue by Mariusthvdb** [arallsopp/hass-hue-icons#170]
**What is the specific model of hue fixture/bulb that you want an icon for**

Not sure if you are open to adding some other devices icons to your repo, so feel free to close if you dont...
It would be way cool though if you would ;-)

As per title, Id love an icon for the Apple HomePod device, more particular the mini variant

**Provide a URL that points to an image of this fixture/bulb**

These are from the Apple support page, but I guess there are even better images on the net

![images-2](https://user-images.githubusercontent.com/33354141/168006623-dacb5cfc-410f-4269-be9e-e90aaa5dbe8d.png)
![images](https://user-images.githubusercontent.com/33354141/168006624-30d0815d-7bcc-4f66-940b-2acd2dc10d6b.png)

**Additional context**

Thanks if you would consider!

**Comment by arallsopp** [comment]
Reminds me...  I'm supposed to be creating a custom repo for these things. I won't be adding that one here, but I will flag it for a custom one.

**Comment by Mariusthvdb** [comment]
please see https://github.com/Mariusthvdb/Custom-icons where I hope to credit you correctly? I have had these custom icons in 4 different resources And the huge Font awesome Pro, and finally found the time to figure things out a bit. Maybe safe yourself the time for the custom repo?

**Comment by arallsopp** [comment]
How about I create one and send it across as a first contribution:)

**Comment by Mariusthvdb** [comment]
wow, I would be honored !!
thanks if you would. so appreciated.

**Comment by arallsopp** [comment]
Added icons and created a pull request for you here: https://github.com/Mariusthvdb/Custom-icons/pull/1

**Comment by Mariusthvdb** [comment]
sure, and thanks!

Im not much of an icon creator, but if people have an .svg, we can easily add those, no problem at all!

**Comment by arallsopp** [comment]
yeah, just open the path and add the svg descriptor to it, then save as whatever.svg.

eg:

`path: "M14.2,11.2l0.1,11L9.9,23l-1.8-0.2V11.9l3.7-0.8l0,0l1.7-10L14.1,1l1.8,0.2L14.2,11.2z"`

becomes:

`<svg viewBox="0 0 24 24" height="24px" width="24px" fill="#44739e" xmlns="http://www.w3.org/2000/svg"><path d="M14.2,11.2l0.1,11L9.9,23l-1.8-0.2V11.9l3.7-0.8l0,0l1.7-10L14.1,1l1.8,0.2L14.2,11.2z"/></svg>`

**Comment by Mariusthvdb** [comment]
yes, but in which editor is that? a mere text editor?

**Comment by arallsopp** [comment]
Actually, @Mariusthvdb, just realised you can do it directly within github.

- Click 'Add file' at the top of the github screen in a repo you have control over, in the relevant folder
- paste the `<svg....` opener in, 
- then your path
- finally `"/></svg>` 
- save it as whatever.svg
