### ISSUE TITLE
Icon Request wall-lantern-off

### ISSUE THREAD

**Issue by tm24fan8** [arallsopp/hass-hue-icons#171]
**What is the specific model of hue fixture/bulb that you want an icon for**

No new device, I am looking for an off state for the existing hue:wall-lantern icon. Thanks!

**Comment by arallsopp** [comment]
Am on it. Thanks for the suggestion, Tony.

**Comment by arallsopp** [comment]
Thanks again @tm24fan8. It'll be in release [v.1.2.29](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.29).

| Icon | Name |
| :--- | :--- |
| ![hue:wall-lantern-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wall-lantern-off.svg)| hue:wall-lantern-off|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 351 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
