### ISSUE TITLE
Icon Request [Downlight]

### ISSUE THREAD

**Issue by keshirkey** [arallsopp/hass-hue-icons#176]
**What is the specific model of hue fixture/bulb that you want an icon for**

Recessed downlight (4-inch)

**Provide a URL that points to an image of this fixture/bulb**

https://www.philips-hue.com/en-us/p/hue-white-ambiance-downlight-4-inch/5996311U5

**Additional context**

I'd appreciate an icon for a single recessed downlight, as well as a group. Thanks!

**Comment by arallsopp** [comment]
Would these existing icons cover it, or would you prefer something more specific be drawn up?

| Icon | Name | 
| :--- | :--- |
| ![hue:ceiling-flush-circular](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-flush-circular.svg)| hue:ceiling-flush-circular |
| ![hue:bulb-group-ceiling-flush-circular](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-ceiling-flush-circular.svg)|hue:bulb-grou-ceiling-flush-circular |

I can certainly draw some more, but these look awfully close to the image you've linked.

<img width="124" alt="image" src="https://user-images.githubusercontent.com/2462104/169891743-0f622d28-1cef-4dd4-a72a-30034eb4bd0d.png">

I don't mind either way, so just let me know.

**Comment by keshirkey** [comment]
No, that's perfect. I must have missed those. Thanks!

**Comment by arallsopp** [comment]
Marvellous. Your others are all done now, I believe. Will close this out now. Thanks for helping improve hass hue icons!

**Comment by keshirkey** [comment]
You are amazing. Thank you so much!
