### ISSUE TITLE
Icon Request [Candelabra & Filament Combo]

### ISSUE THREAD

**Issue by keshirkey** [arallsopp/hass-hue-icons#177]
**What is the specific model of hue fixture/bulb that you want an icon for**

E12 & G25 Filament

**Provide a URL that points to an image of this fixture/bulb**

https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-single-bulb-e12/046677556969
https://www.philips-hue.com/en-us/p/hue-white-ambiance-filament-1-pack-a19-e26-filament-standard/046677563578

**Additional context**

I'd appreciate a group icon with an upward-facing E12 Candelabra bulb and a hung G25 Filament bulb.. Thanks!

**Comment by arallsopp** [comment]
The e26 (its an e27 in the UK, oddly) filament you've linked doesn't really have an icon at present, as I've been using the G25 variant for all globe shaped instances.

| Icon | Name |
| :--- | :--- | 
| ![hue:bulb-filament](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/bulb-filament.svg)| hue:bulb-filament |
| ![hue:bulb-filament-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-filament-hung.svg)| hue:bulb-filament-hung |

Worth adding an E26 one as well?

**Comment by arallsopp** [comment]
The group will be based around this:
![Uploading image.png…]()

**Comment by arallsopp** [comment]
To come in next release:

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-candle-filament-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-candle-filament-hung.svg)| hue:bulb-group-candle-filament-hung|
