### ISSUE TITLE
Off states for recent icons?

### ISSUE THREAD

**Issue by sarrandalls** [arallsopp/hass-hue-icons#178]
Hi Andy.

Can we have an 'off' icon for:

- bulb-br30-hung-off
- bulb-br30-off
- bulb-filament-a19-hung-off
- bulb-filament-a19-off
- bulb-group-br30-hung-off
- bulb-group-br30-off
- bulb-group-spot-hung-off
- bulb-spot-hung-off
- ceiling-devere-off

There's no particular urgency, but I know these are coming in.

**Comment by arallsopp** [comment]
Closing this, pending the next release.
