### ISSUE TITLE
Off for bollards and wall-appear

### ISSUE THREAD

**Issue by sarrandalls** [arallsopp/hass-hue-icons#180]
**What is the specific model of hue fixture/bulb that you want an icon for**
Hello,

Would it be possible to have off versions of:

- bollard
- bulb-group-bollard
- wall-appear
- wall-appear-group

No rush. You can use the existing icons, but with a slash through them.

Thanks.

**Comment by arallsopp** [comment]
Thanks for raising this Sarah. These are planned for the next release:

| Icon | Name |
| :--- | :--- |
| ![hue:wall-appear-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wall-appear-off.svg)| hue:wall-appear-off|
| ![hue:wall-appear-group-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wall-appear-group-off.svg)| hue:wall-appear-group-off|
| ![hue:bollard-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bollard-off.svg)| hue:bollard-off|
| ![hue:bulb-group-bollard-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-bollard-off.svg)| hue:bulb-group-bollard-off|


I'm battling a HACS validation issue at the moment, so can't say when the release will come.
