### ISSUE TITLE
Icon Request [name of fixture]

### ISSUE THREAD

**Issue by TaFfinSki** [arallsopp/hass-hue-icons#181]
Hai Andy.You have already produced some amazing icons for me in the hue style. Once again. thanks.
Really like your work....amazing!
![image](https://user-images.githubusercontent.com/97610446/170710014-eaf7bd27-7429-4203-ba01-121084650260.png)

can you put a diagional through them so they seem off?

I'd really like you to see my dashboard, since it is 90% based on your icons.
where can I show off?

**Comment by arallsopp** [comment]
I see you. Yep, motion sensor off states coming up. Glad to hear you're getting good use of the icons. It takes time to draw them, so its great to know they're in use.

There's a [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource) over here that'll take a screenshot. I'd love to see what you're doing with it.

**Comment by arallsopp** [comment]
Thanks for the suggestion @TaFfinSki. 

These will be bundled into the next daily release.

| Icon | Name |
| :--- | :--- |
| ![hue:motion-sensor-temperature-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/motion-sensor-temperature-off.svg)| hue:motion-sensor-temperature-off|
| ![hue:motion-sensor-movement-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/motion-sensor-movement-off.svg)| hue:motion-sensor-movement-off|
| ![hue:motion-sensor-luminance-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/motion-sensor-luminance-off.svg)| hue:motion-sensor-luminance-off|
| ![hue:motion-sensor-luminance-alt-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/motion-sensor-luminance-alt-off.svg)| hue:motion-sensor-luminance-alt-off|


You can see all the motion icons together, using this [iconfinder link](https://arallsopp.github.io/hass-hue-icons/docs/build/tester/iconfinder.html?search=motion)

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 383 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
