### ISSUE TITLE
Bloom off and bloom-group off

### ISSUE THREAD

**Issue by wrt54g** [arallsopp/hass-hue-icons#182]
**What is the specific model of hue fixture/bulb that you want an icon for**
Bloom off and bloom group off

**Provide a URL that points to an image of this fixture/bulb**
https://www.assets.signify.com/is/image/PhilipsLighting/32845bd66b824fc0995fab0300dec5a4

**Additional context**

**Existing icon(s)**
bloom
bloom-group

**Comment by arallsopp** [comment]
Ah. You just missed tonight's request window. It'll be in tomorrow! :)

**Comment by arallsopp** [comment]
Thanks for the suggestion. These have gone into release [v.1.2.35](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.35) alongside the bridge off request

| Icon | Name |
| :--- | :--- |
| ![hue:bloom-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bloom-off.svg)| hue:bloom-off|
| ![hue:bloom-group-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bloom-group-off.svg)| hue:bloom-group-off|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 386 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
