### ISSUE TITLE
Sultan 4 group

### ISSUE THREAD

**Issue by wrt54g** [arallsopp/hass-hue-icons#184]
**What is the specific model of hue fixture/bulb that you want an icon for**
Sultan group with 4 bulbs.

**Existing icons**
bulb-sultan

**Comment by arallsopp** [comment]
Its coming...

<img width="451" alt="image" src="https://user-images.githubusercontent.com/2462104/171133151-1ec90436-5351-4475-9f90-91c2bef557db.png">

**Comment by arallsopp** [comment]
Thanks for the suggestion @wrt54g. It'll be in release [v.1.2.36](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.36). Got a better technique now. Clone the shape, scale and offset, then outline with 1px before pathfinding the outline away. Gives me consistent 1px spacing between all items easily.

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-sultan-4](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-sultan-4.svg)| hue:bulb-group-sultan-4|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 387 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by wrt54g** [comment]
Thanks
![image](https://user-images.githubusercontent.com/85389871/171183739-8cc7c639-3c52-481f-a16d-afe32a6a3301.png)

**Comment by arallsopp** [comment]
Looking good, mate. Glad I could help.

**Comment by wrt54g** [comment]
I use this icon for 4 light bulbs all arranged next to each other in 1 fixture. "Keuken" means "Kitchen" in Dutch btw.
