### ISSUE TITLE
Hung version of the four bulb sultan?

### ISSUE THREAD

**Issue by sarrandalls** [arallsopp/hass-hue-icons#186]
Hi. 

Can we have the hung version of that four bulb sultan bundled into a release please? 

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-sultan-4](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-sultan-4.svg)| hue:bulb-group-sultan-4|

**Comment by arallsopp** [comment]
Morning Sarah.

This has been bundled into [v.1.2.37](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.37).

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-sultan-4-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-sultan-4-hung.svg)| hue:bulb-group-sultan-4-hung|

Thanks for documenting.
