### ISSUE TITLE
4 bulb sultan off and hung off

### ISSUE THREAD

**Issue by wrt54g** [arallsopp/hass-hue-icons#187]
**What is the specific model of hue fixture/bulb that you want an icon for**
Off version for these icons:
bulb-group-sultan-4
bulb-group-sultan-4-hung

**Comment by arallsopp** [comment]
Ok. Will add to the next release.

**Comment by wrt54g** [comment]
> Ok. Will add to the next release.

Great

**Comment by arallsopp** [comment]
Coming up...
<img width="331" alt="image" src="https://user-images.githubusercontent.com/2462104/172138707-e9f03708-10b5-407a-a7b7-7adb12962b19.png">

**Comment by arallsopp** [comment]
Thanks again, @wrt54g

The hung variants will be introduced in tomorrow's release [v.1.2.38](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.38).

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-sultan-4-hung-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-sultan-4-hung-off.svg)| hue:bulb-group-sultan-4-hung-off|
| ![hue:bulb-group-sultan-4-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-sultan-4-off.svg)| hue:bulb-group-sultan-4-off|
