### ISSUE TITLE
Icon Request filament candle group and hung filament candle

### ISSUE THREAD

**Issue by H3xF2x** [arallsopp/hass-hue-icons#188]
I would like to have a hung filament candle - "hue:bulb-filament-candle" rotated.
And a goup of filament candle in hung.

Thanks a lot for your work

**Comment by arallsopp** [comment]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/2462104/172142288-622fc784-7969-4109-8015-22e6bc8b5ba3.png">
Are they on a string, or in fixtures, @H3xF2x? Trying to work out if left or right image is better for you.

**Comment by H3xF2x** [comment]
They are in fixtures in a 100+ years old chandelier. The right image would be better for me, thanks.

**Comment by arallsopp** [comment]
> They are in fixtures in a 100+ years old chandelier. The right image would be better for me, thanks.

Wow. Sounds beautiful, @H3xF2x. I love that interplay of classic and modern technology. Share a pic if you get a chance?

Your request will be in tomorrow's release of [v.1.2.38](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.38).

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-filament-candle-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-filament-candle-hung.svg)| hue:bulb-group-filament-candle-hung|
| ![hue:bulb-filament-candle-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-filament-candle-hung.svg)| hue:bulb-filament-candle-hung|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 392 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by H3xF2x** [comment]
> Share a pic if you get a chance?

![IMG_1307](https://user-images.githubusercontent.com/93159543/172146942-5abee6ce-9d1e-402a-97d6-8e7eb5e21f65.jpeg)

**Comment by arallsopp** [comment]
Gorgeous bit of art nouveau, there. Wow.
