### ISSUE TITLE
Icons for Hue App scenes?

### ISSUE THREAD

**Issue by sarrandalls** [arallsopp/hass-hue-icons#189]
Can we have the relax, reading, concentrate, night light and energize scenes from the hue app
![IMG_E4C106A31996-1](https://user-images.githubusercontent.com/104910433/172203832-0cfdb719-ac68-4d7d-9939-a5b3deaecf70.jpeg)
?

**Comment by arallsopp** [comment]
Working on it... It'll take a little time to get these going. I've a release planned for tomorrow, so hope to be able to bundle these into that if I can get them in today.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/2462104/172204090-15c2754d-ed33-4a12-9991-5fd7768d4078.png">

**Comment by arallsopp** [comment]
Thanks @sarrandalls. These will make their way to release [v.1.2.38](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.38) tomorrow morning.

| Icon | Name |
| :--- | :--- |
| ![hue:scene-concentrate](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/scene-concentrate.svg)| hue:scene-concentrate|
| ![hue:scene-nightlight](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/scene-nightlight.svg)| hue:scene-nightlight|
| ![hue:scene-relax](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/scene-relax.svg)| hue:scene-relax|
| ![hue:scene-read](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/scene-read.svg)| hue:scene-read|
| ![hue:scene-energize](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/scene-energize.svg)| hue:scene-energize|


### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 398 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
