### ISSUE TITLE
Add 4 new icons

### ISSUE THREAD

**Issue by HunterX86** [arallsopp/hass-hue-icons#191]
**What is the specific model of hue fixture/bulb that you want an icon for**
sultan group

**Provide a URL that points to an image of this fixture/bulb**
[bulb-group-alt.zip](https://github.com/arallsopp/hass-hue-icons/files/8873792/bulb-group-alt.zip)

**Additional context**

**Comment by arallsopp** [comment]
Hey @HunterX86. Did you create these? 

Got to be honest, I'm apprehensive about adding icons from third parties, as I've had my own work here stolen without credit, and it leaves a bad taste in the mouth. Even more annoyingly, its left me mistrusting of people, which is no fun.

I'd be happy to create a 3 bulb group of sultans in hung/off variants. There's always a fair chunk of clean up to get things into a single path svg file anyway, so its not particularly extra work. 

If these are your design, I'll credit you for their origination. If not, I'll credit you for the suggestion.

OK?

**Comment by HunterX86** [comment]
Thnx for adding all of the icons.
You can give me credits for my creations.

> Also, am sorry to be repaying your contribution with unexpected queries. I'll get these icons for you one way or another, but need to be sure I'm not about to lose the seat on my high horse :)

I don't mind that, i do it for fun.

**Comment by arallsopp** [comment]
Sorry, been travelling.

Looking to add these to the next release. Am tweaking a little based upon the standards I've used in the other icons created here, and will name them bulb-group-sultan-3 / hung / off

**Comment by HunterX86** [comment]
that's fine.
thnx.

**Comment by HunterX86** [comment]
that's great thnx.
i'm closing this is issue.
