### ISSUE TITLE
Icon off ?

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#193]
**What is the specific model of hue fixture/bulb that you want an icon for**

**Provide a URL that points to an image of this fixture/bulb**

**Additional context**

Hallo can you dis icon to off ? 

1.hue:table-wash

**Comment by arallsopp** [comment]
Business travel imminent, but will see if I can get this in first. If not, I'll post an update from the other side of the atlantic :)

**Comment by arallsopp** [comment]
Thanks again @jrspowers. It'll be in release [v.1.2.40](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.40).

| Icon | Name |
| :--- | :--- |
| ![hue:table-wash-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/table-wash-off.svg)| hue:table-wash-off|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 405 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by jrspowers** [comment]
good luck on business trip and thanks for making this one

**Comment by arallsopp** [comment]
You're welcome.
