### ISSUE TITLE
hue tap dial? (Released today)

### ISSUE THREAD

**Issue by sarrandalls** [arallsopp/hass-hue-icons#194]
**What is the specific model of hue fixture/bulb that you want an icon for**

Philips Hue Tap Dial

**Provide a URL that points to an image of this fixture/bulb**
https://www.theverge.com/2022/6/21/23176531/philips-hue-dial-remote-go-lamp-track-lighting-price-date

**Additional context**
This got released in EU today.

**Comment by sarrandalls** [comment]
On it. 

Just missed today's release, so likely to make its way up in the next few days. I'll see if there are other devices in that press release, as may as well jump ahead.
<img width="549" alt="image" src="https://user-images.githubusercontent.com/104910433/174802829-26fc1f2b-2909-46c9-bb22-e2b154848f63.png">

**Comment by arallsopp** [comment]
Here's how it might look:

| Icon | Name |
| :--- | :--- |
| ![hue:tap-dial](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/tap-dial.svg)| hue:tap-dial|

**Comment by arallsopp** [comment]
Looking at adding the go portable table also
<img width="448" alt="image" src="https://user-images.githubusercontent.com/2462104/174808056-dea81180-2222-43e0-9ccc-085e6c2c17a2.png">

**Comment by arallsopp** [comment]
Maybe: 

| Icon | Name |
| :--- | :--- |
| ![hue:go-portable-table](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/go-portable-table.svg)| hue:go-portable-table|

**Comment by arallsopp** [comment]
Alternate version of the go portable... Thinking on this...
 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/2462104/174810628-0ce6fbfb-87b7-43c1-9e89-ed638200c750.png">

**Comment by arallsopp** [comment]
Alternate version looks like this:

| Icon | Name |
| :--- | :--- |
| ![hue:go-portable-table-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/go-portable-table-alt.svg)| hue:go-portable-table-alt|

**Comment by arallsopp** [comment]
Also looking at the Perifo track system. Will add icons for two of these:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/2462104/175574178-f5671cc0-090a-4dbe-954f-62dc5b4fa337.png">

**Comment by arallsopp** [comment]
| Icon | Name |
| :--- | :--- |
| ![hue:perifo-spot](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/perifo-spot.svg)| hue:perifo-spot|

**Comment by arallsopp** [comment]
Thanks @sarrandalls. The new icons are in release [v.1.2.41](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.41).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 409 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
