### ISSUE TITLE
Change versioning to not have a . (dot) after v for changelogs in HACS

### ISSUE THREAD

**Issue by mvdwetering** [arallsopp/hass-hue-icons#195]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more a nice to have.

HACS can display changelogs from installed version to latest version when updates are available however that only seems to work when the versions are formatted like "v1.2.3"(note no dot after the "v"), maybe other formats are supported but could not find that in the HACS docs. I just found out because I made a typo in the versioning of my own custom_component and noticed the changelog did not display for that one.

**Describe the solution you'd like**
Have versions like "v1.2.3" instead of "v.1.2.3" or another format compatible with HACS.

**Describe alternatives you've considered**
Lookup changelogs manually.

**Additional context**
Like I said, just a nice to have. If it is a hassle, just ignore this request.

**Comment by arallsopp** [comment]
Howdo. 

I need to work out if that is going to cause any upset elsewhere. Will maybe try it with the next release and see where it takes us. 

Thank you for the suggestion!

**Comment by arallsopp** [comment]
OK. New release up. Let's see if things improve between this and the next one! :)
