### ISSUE TITLE
Off-Variant

### ISSUE THREAD

**Issue by IgneaX** [arallsopp/hass-hue-icons#197]
Hi,
can you please add an Off-variant for hue:iris?

Thank you for your good job and best regards

**Comment by arallsopp** [comment]
Will do! Am away from my machine at the moment, but it’ll come.

**Comment by arallsopp** [comment]
Thanks for the suggestion, @IgneaX. Your icon is in release [v1.2.42](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.42).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 410 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
