### ISSUE TITLE
Lightguide bulbs

### ISSUE THREAD

**Issue by sarrandalls** [arallsopp/hass-hue-icons#198]
**What is the specific model of hue fixture/bulb that you want an icon for**
Philips Hue Lightguide bulbs, that have just been 'leaked'

**Provide a URL that points to an image of this fixture/bulb**
https://hueblog.com/2022/08/26/philips-hue-lightguide-no-smart-home-lamps-have-ever-been-so-chic/

![image](https://user-images.githubusercontent.com/104910433/186864841-12dc73a7-9493-47a3-9a06-5bd3e99d6c8c.png)

These look to be coming soon. Would be great if we could get the jump on them as I know they'll be on my list to buy!

Thanks.

**Comment by arallsopp** [comment]
I see them, and I'm on iit!

<img width="515" alt="image" src="https://user-images.githubusercontent.com/2462104/186866605-cacb0f35-aad5-48e3-9301-9cf941e5a8fb.png">

**Comment by arallsopp** [comment]
Thanks again, @sarrandalls.

These bulbs will be in release [v1.2.43](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.43).

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-lightguide-flask](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-lightguide-flask.svg)| hue:bulb-lightguide-flask|
| ![hue:bulb-lightguide-round](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-lightguide-round.svg)| hue:bulb-lightguide-round|
| ![hue:bulb-lightguide-oval](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-lightguide-oval.svg)| hue:bulb-lightguide-oval|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 413 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
