### ISSUE TITLE
Group for hue:recessed-ceiling

### ISSUE THREAD

**Issue by cloudbr34k84** [arallsopp/hass-hue-icons#199]
Can you please make a group hue:recessed-ceiling?

**Comment by arallsopp** [comment]
How about this?

<img width="530" alt="image" src="https://user-images.githubusercontent.com/2462104/187000133-d0904484-82a8-47a2-87e2-1cfe878ad656.png">

I normally overlap them, but the recessed ceiling is flat enough to stack without eclipsing.

**Comment by arallsopp** [comment]
Thanks. It'll be in release [v1.2.43](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.43). Should be up tonight.


| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-recessed-ceiling](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-recessed-ceiling.svg)| hue:bulb-group-recessed-ceiling|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 414 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by cloudbr34k84** [comment]
Thank you for such a speedy turn around! I might have some more as i keep designing

**Comment by arallsopp** [comment]
No problem, @cloudbr34k84. Happy to solve for most things and always good to see the icons being used.

**Comment by cloudbr34k84** [comment]
![Screenshot_20220828-194451](https://user-images.githubusercontent.com/58960644/187067858-56c0afbd-e70f-4c1e-96af-bcd6fb22f00f.png)
Yeah for my room Cards to show that this light switch controls multiple downlights

**Comment by arallsopp** [comment]
Neat. 

My rooms just have icons for purpose, but then I'm splitting my dash out by function as well as by room.

 ![image](https://user-images.githubusercontent.com/2462104/187067945-9cdea042-67bb-4afe-a36d-d13ff71ef372.png)

![image](https://user-images.githubusercontent.com/2462104/187067973-1a9de4d3-7d93-4d09-a819-5c23aa6b33bb.png)

**Comment by cloudbr34k84** [comment]
![Screenshot_20220828-195647](https://user-images.githubusercontent.com/58960644/187068310-a1579945-f657-4469-94f4-aaf99e133453.png)
![Screenshot_20220828-195700](https://user-images.githubusercontent.com/58960644/187068320-92968e80-815f-4c36-bc45-7f8404dd9efb.png)
![Screenshot_20220828-195710](https://user-images.githubusercontent.com/58960644/187068321-81b69845-0c41-4581-b58b-707a4016a685.png)
![Screenshot_20220828-195727](https://user-images.githubusercontent.com/58960644/187068322-f3a86bba-c5d4-40f2-8454-7edc71619cf7.png)

**Comment by arallsopp** [comment]
Wow. You are so far ahead of me. That's an amazing installation!

**Comment by cloudbr34k84** [comment]
Lol I only started in January. I don't how to code. It's all just copy and paste. I'm sure there are better ways but I'm happy.
