### ISSUE TITLE
Icon Request - Lucca wall light in Off state

### ISSUE THREAD

**Issue by TonyKrzyz** [arallsopp/hass-hue-icons#201]
Could you consider adding an "Off" state version equivalent for the "hue:wall-lucca" please? While there are many "off" icons, there are none for the Lucca outdoor lights.

Relates to this light fitting: https://www.philips-hue.com/en-gb/p/hue-white-lucca-outdoor-wall-light/1740193P0

Thanks.

**Comment by arallsopp** [comment]
Yep. I hear you. Gone midnight here but should be able to get to this tomorrow morning.

**Comment by arallsopp** [comment]
Thanks for the suggestion @TonyKrzyz. Your icons are in release [v1.2.44](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.44). Please let me know if there's anything else I can help you with.

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 417 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by TonyKrzyz** [comment]
Hey, thanks for getting back to me, really wasn't expecting a response that quickly and of course would never expect anyone to be doing this stuff so late in the day!I realised after there are a couple more that would be useful, for me at least, so when I get the chance I'll do requests for those too so if you want to wait and do them all at once of course that's fine, it's not like it's critical or urgent. (Assuming you're happy to do them at all, I appreciate it's work for you!)Thanks Andy, really appreciate it. 
-------- Original message --------From: Andy Allsopp ***@***.***> Date: 23/09/2022  00:20  (GMT+00:00) To: arallsopp/hass-hue-icons ***@***.***> Cc: TonyKrzyz ***@***.***>, Author ***@***.***> Subject: Re: [arallsopp/hass-hue-icons] Icon Request - Lucca wall light in Off
  state (Issue #201) 
Yep. I hear you. Gone midnight here but should be able to get to this tomorrow morning.

**Comment by arallsopp** [comment]
Looking forward to helping you. It feels good to be able to pay back to the HA community.
