### ISSUE TITLE
Lutron Pico Remote

### ISSUE THREAD

**Issue by sdholden28** [arallsopp/hass-hue-icons#202]
**What is the specific model of hue fixture/bulb that you want an icon for**
_**Lutron Pico Remote PJ2-3BRL-WH-L01R (I know this is not a Hue product, but it seems many people, including myself, use these pico remotes to control Hue products, so I think this is a relevant place to include an icon.**_

**Provide a URL that points to an image of this fixture/bulb**
_**https://images.app.goo.gl/J8Y1kZfyafZ1bzFr7**_

**Additional context**

**Comment by arallsopp** [comment]
Tell you what... I'll draw the icon and if it ends up falling on the side of not hue, I'll offer it to another repo. Ok?

**Comment by sdholden28** [comment]
Sounds great to me. Thank you very much!

**Comment by arallsopp** [comment]
How about something like this?

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/2462104/192320632-bcb921e4-4092-4568-9735-d4db7b8d7e48.png">

**Comment by arallsopp** [comment]
Figured I'd add them with button presses lit up to give us some future proofing. I'll recommend these for inclusion in https://github.com/Mariusthvdb/custom-icons

| Icon | Name |
| :--- | :--- |
| ![lutron-pico](https://user-images.githubusercontent.com/2462104/192548718-6c138925-e56e-4f34-809b-249cd5425d73.svg) | lutron-pico |
| ![lutron-pico-b1](https://user-images.githubusercontent.com/2462104/192548700-1902ddde-f9ec-4f9e-89f7-0a15cd683c84.svg) | lutron-pico-b1 |
| ![lutron-pico-b2](https://user-images.githubusercontent.com/2462104/192548708-58c276fb-7599-4a4d-8c49-e64f2a7e2489.svg) | lutron-pico-b2 |
| ![lutron-pico-b3](https://user-images.githubusercontent.com/2462104/192548710-93f07eef-2625-4f77-96f5-21825b8f1e39.svg) | lutron-pico-b3 |
| ![lutron-pico-b4](https://user-images.githubusercontent.com/2462104/192548714-10e0baba-e1e2-40ef-b8e6-838880e4b9a3.svg) | lutron-pico-b4 |
| ![lutron-pico-b5](https://user-images.githubusercontent.com/2462104/192548716-346cbb90-6974-4d87-99dc-3ff7752a067b.svg) | lutron-pico-b5 |

**Comment by sdholden28** [comment]
Thank you!

**Comment by arallsopp** [comment]
Marking as closed. I'm glad I could get you these icons. Happy holidays!
