### ISSUE TITLE
Hue icons off ?

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#203]
hello would you like to make this icon an off version of thanks already ?

1. pendant-devote
2. pendant-devote-solid
3. pendant-devote-two-
4. pendant-devote-two-solid
5. pendant-devote-three
6. pendant-devote-three-solid
7.  bulb-group-go-sultan
8. daylo-wall

**Comment by arallsopp** [comment]
Ok. Here's the proposed additions for the next release, @jrspowers. I see there's another issue open, so might fix both in a single release. Got to step away shortly, so if I push this one first, rest assured the other will come.

| Icon | Name |
| :--- | :--- |
| ![hue:pendant-devote-solid-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-devote-solid-off.svg)| hue:pendant-devote-solid-off|
| ![hue:pendant-devote-three-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-devote-three-off.svg)| hue:pendant-devote-three-off|
| ![hue:pendant-devote-three-solid-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-devote-three-solid-off.svg)| hue:pendant-devote-three-solid-off|
| ![hue:pendant-devote-two-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-devote-two-off.svg)| hue:pendant-devote-two-off|
| ![hue:pendant-devote-two-solid-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-devote-two-solid-off.svg)| hue:pendant-devote-two-solid-off|
| ![hue:daylo-wall-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/daylo-wall-off.svg)| hue:daylo-wall-off|
| ![hue:bulb-group-go-sultan-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-go-sultan-off.svg)| hue:bulb-group-go-sultan-off|

**Comment by arallsopp** [comment]
These are now available in [v1.245](https://github.com/arallsopp/hass-hue-icons/releases/tag/v1.2.45). Thanks for the suggestion.

**Comment by jrspowers** [comment]
Thanks man 🙂

**Comment by jrspowers** [comment]
hello 

hello I see you forgot to make this hue:pendant-devote in the off version if you can still make it ?  thanks in advance!

**Comment by arallsopp** [comment]
Apologies. Will action that.

**Comment by jrspowers** [comment]
thanks & that group of the other question is that okay?
