### ISSUE TITLE
Group icon for Lucca (wall)

### ISSUE THREAD

**Issue by lassir** [arallsopp/hass-hue-icons#205]
Could icon for a group of two `hue:wall-lucca` lights be added to the icon pack? 

**What is the specific model of hue fixture/bulb that you want an icon for**

Lucca (wall)

**Provide a URL that points to an image of this fixture/bulb**

`hue:wall-lucca`

<img src="https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/wall-lucca.svg" width="64px" />

**Comment by arallsopp** [comment]
Thanks again @lassir. Your icon will be in release [v1.2.47](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.47).

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-wall-lucca](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-wall-lucca.svg)| hue:bulb-group-wall-lucca|
