### ISSUE TITLE
Icon Request - String lights

### ISSUE THREAD

**Issue by AndreasStefanDahl** [arallsopp/hass-hue-icons#209]
**What is the specific model of hue fixture/bulb that you want an icon for**

String lights, which is an icon that was added with the release of their Festavia string lights. 

**Provide a URL that points to an image of this fixture/bulb**

It's difficult to find vector images of it. 

Here is the product page: https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-festavia-string-lights/046677580148

Here's a screenshot from their app: 
![image](https://user-images.githubusercontent.com/4296837/203980672-3b267e51-dfca-458b-b933-95c8bca6b5c0.png)

**Comment by arallsopp** [comment]
Thanks for the screenshot, as that makes it much easier. Am on it!

**Comment by arallsopp** [comment]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/2462104/204127361-c66ef0d7-2ca9-402c-a23c-57b866c439f0.png">
Its getting there. This detail is sub 1px though, so I'm going to have to take a treatment on it.

**Comment by AndreasStefanDahl** [comment]
Looks great so far! 

Here's another screenshot that might offer slightly more details. 

![Screenshot_20221127-101214~2](https://user-images.githubusercontent.com/4296837/204127519-0b343f96-e72f-49e5-b5cc-059cb5016875.png)

**Comment by arallsopp** [comment]
Definitely helps. I'm working my way towards this:
| Icon | Name |
| :--- | :--- |
| ![hue:festivia](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/festivia.svg)| hue:festivia|

**Comment by arallsopp** [comment]
If that works for you as a design, @AndreasStefanDahl, let me know and I'll create a release.

**Comment by AndreasStefanDahl** [comment]
Looks great! 

I guess the only thing would be if it should be called festavia or string lights?

**Comment by arallsopp** [comment]
Keywords are string and Christmas. Festavia was a typo on my part :)

**Comment by AndreasStefanDahl** [comment]
Then it's all good! Great job and thanks for the quick fix

**Comment by arallsopp** [comment]
Thanks for the suggestion @AndreasStefanDahl.

Your light will be in release [v1.2.48](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.48).

| Icon | Name | Keywords
| :--- | :--- | :--- |
| ![hue:festavia](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/festavia.svg)| hue:festavia| light, christmas, string

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 428 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
