### ISSUE TITLE
LEDVANCE ZIGBEE SMART+ LED GARDENPOLE

### ISSUE THREAD

**Issue by twelve-cgn** [arallsopp/hass-hue-icons#21]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

LEDVANCE ZIGBEE SMART+ LED GARDENPOLE

**Provide a URL that points to an image of this fixture/bulb**

https://shop.ledvance.com/products/smart-gardenpole-multicolour-basic-set-eu

**Additional context**

It would be a little bit like hue:wall-appear with different top and no wall mount. Or like a hue:pillar-tuar with different top.

**Comment by arallsopp** [comment]
Hi @twelve-cgn. This library is for Philips Hue appliances and devices, so the LEDVANCE kit you've linked doesn't really belong.

Good thinking on wall-appear and pillar-tuar. Wonder if you might get closer with hue:bollard?

<img src="https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/bollard.svg" width="150px">

**Comment by twelve-cgn** [comment]
> Hi @twelve-cgn. This library is for Philips Hue appliances and devices, so the LEDVANCE kit you've linked doesn't really belong.
> 
> Good thinking on wall-appear and pillar-tuar. Wonder if you might get closer with hue:bollard?
> 
> <img alt="" width="150px" src="https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/bollard.svg">

Great. I missed it. So unexpected in the first row.
