### ISSUE TITLE
Icon Request [Hue Festavia]

### ISSUE THREAD

**Issue by yvansandoz** [arallsopp/hass-hue-icons#210]
**What is the specific model of hue fixture/bulb that you want an icon for**

**[Provide a URL that points to an image of this fixture/bulb](https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-festavia-string-lights/046677580148)**

**Additional context**

**Comment by arallsopp** [comment]
Welcome @yvansandoz.

That link points to festavia string lights, if I'm seeing it correctly. These are already in the current release [v1.2.48] (https://github.com/arallsopp/hass-hue-icons/releases/tag/v1.2.48).

| Icon | Name | Keywords
| :--- | :--- | :--- |
| ![hue:festavia](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/festavia.svg)| hue:festavia| light, christmas, string|

Please let me know if there's anything you need or I've misunderstood.

**Comment by arallsopp** [comment]
marking for close as a duplicate of #209. Please feel free to re-open if there's something I've missed.

**Comment by yvansandoz** [comment]
Sorry, I didn't see this option. In my head I was looking for a pine tree with lights on it. 
Take care,
Yvan
