### ISSUE TITLE
Icon Request Lily/Lily XL alternate mount

### ISSUE THREAD

**Issue by alvinchen1** [arallsopp/hass-hue-icons#211]
Thanks for your work, Lily and Lily XL has an alternate mount which I was wondering if I could request.  

Lily and Lily XL without the removable round flat base, and mounted on an included stick.

For Lily XL, the manual, page 7 and 8 shows the alternate mount (without the Lily XL cover)
https://www.assets.signify.com/is/content/Signify/df122e222a814c1191bcae9200ccc4c4

For Lily, the website shows it under Versatile mounting options, https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-lily-outdoor-spot-light/1741730V7#faq

<img width="322" alt="image" src="https://user-images.githubusercontent.com/26409535/213476344-7aed8064-db3c-43b8-9f05-071ad08043a4.png">

Thanks as always!

**Comment by arallsopp** [comment]
Cheers. I'll take a look.

**Comment by arallsopp** [comment]
Assuming you're good with these, I'll package up into a new release, @alvinchen1.

| Icon | Name |
| :--- | :--- |
| ![hue:lily-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lily-alt.svg)| hue:lily-alt|
| ![hue:lily-xl-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lily-xl-alt.svg)| hue:lily-xl-alt|

Let me know, yes?

**Comment by alvinchen1** [comment]
Looks great!

**Comment by arallsopp** [comment]
Awesome. I'll link with the release below as soon as its up.

**Comment by arallsopp** [comment]
Thanks again. Your icons are in release [v1.2.49](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.49).
### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 430 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
