### ISSUE TITLE
Icon Request - Rest and Natural Light scenes

### ISSUE THREAD

**Issue by lezmaka** [arallsopp/hass-hue-icons#212]
Hue (recently I think) added two new default scenes - Rest and Natural Light.  Can these be added?

![image](https://user-images.githubusercontent.com/5054745/213745216-53da669f-c99c-414a-a143-474f98557f9d.png)

**Comment by arallsopp** [comment]
Interesting.. I'll take a look and see if I can craft something that looks similar.

**Comment by arallsopp** [comment]
Here's the proposal for 'rest', based upon the size and treatment for scene-read:

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/2462104/213748279-b0d35e28-394f-4c55-8647-d8e7a29209f6.png">

**Comment by arallsopp** [comment]
I'll be building scene-natural-light upon scene-bright, as that has the sun icon in place already.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/2462104/213750215-b6999fc1-09fd-4450-b351-fb4c5654ce78.png">

**Comment by arallsopp** [comment]
There you go, scene-bright on left, new icon in middle, reference on right.
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/2462104/213751030-0c38273c-3769-40db-8cd1-7b4117ef61ba.png">

**Comment by arallsopp** [comment]
I've added your icons to release [v1.2.51](https://github.com/arallsopp/hass-hue-icons/releases/tag/v1.2.51). Let me know if there's anything further you need.

| Icon | Name |
| :--- | :--- |
| ![hue:scene-rest](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/scene-rest.svg)| hue:scene-rest|
| ![hue:scene-natural-light](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/scene-natural-light.svg)| hue:scene-natural-light|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 436 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
