### ISSUE TITLE
Icon Request [Hue Signe (gradient floor) & Hue Play Gradient Tube - Off Icons]

### ISSUE THREAD

**Issue by danm1989** [arallsopp/hass-hue-icons#213]
**What is the specific model of hue fixture/bulb that you want an icon for**

Hue Signe (Gradiant floor) - off variant.
Hue Play Gradient Tube (long/short) - off variant

**Provide a URL that points to an image of this fixture/bulb**

https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/signe-gradient-floor.svg
https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/gradient-tube-long.svg
https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/gradient-tube-short.svg

**Additional context**

If there could be an off variant made for the icons linked on your repot (with the strike through, similar to the rest of the amazing work you have done), that would be fantastic.

**Comment by arallsopp** [comment]
Thanks, I'll take a look.

**Comment by danm1989** [comment]
Yes! This is perfect. Great work, thank you. I look forward to the release.

**Comment by arallsopp** [comment]
Good stuff, your icons are now published as part of [Release 1.2.50](https://github.com/arallsopp/hass-hue-icons/releases/tag/v1.2.50). Thanks for the suggestion.

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 435 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
