### ISSUE TITLE
Icon for multiple floor-spot

### ISSUE THREAD

**Issue by mdehaas** [arallsopp/hass-hue-icons#216]
The single icon is already included and I would like an icon in line with the existing icons representing a group
https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/floor-spot.svg

Thanks in advance for your effort
Kind regards, Marcel

**Comment by arallsopp** [comment]
Thanks for the request. Will put something together tonight and make a new release.

**Comment by arallsopp** [comment]
Thanks for the suggestion, Marcel. 

Your icon is in release [v1.2.51](https://github.com/arallsopp/hass-hue-icons/releases/tag/v1.2.51).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 436 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
