### ISSUE TITLE
Icons for Perifo Cylinder Pendant - please

### ISSUE THREAD

**Issue by dathosim** [arallsopp/hass-hue-icons#231]
Perifo Cylinder Pendant 

**Provide a URL that points to an image of this fixture/bulb**
https://www.philips-hue.com/en-gb/p/hue-white-and-colour-ambiance-perifo-cylinder-pendant/8719514407480

**Additional context**

For home assistant dashboard ! 
We can put 2 types of lamps on The Perifo Rail : 
- Perifo Spot already exist in your set
- Perifo Cylinder Pendant 

Thanks a lot !

**Comment by arallsopp** [comment]
Howdo.

Apologies for lag. Been a little disenfranchised of late having seen a lot of the icons I've been drawing coming up on other repos without accreditation. Makes it hard for people to find me and ask for icons. Hopefully I can get to these shortly.  I'll add a preview when I have something mocked up.

**Comment by arallsopp** [comment]
I'm thinking along the lines of this:
<img width="402" alt="image" src="https://github.com/arallsopp/hass-hue-icons/assets/2462104/f97a42b9-7b7a-4520-bc4c-aee14302080d">

I know it doesn't include the cable drop, but I think given the space we have and the icon it'll go along with (perifo spot) its probably best to just differentiate by direction. I'll stage this one. Let me know if you think it needs a tweak.

Andy.

**Comment by arallsopp** [comment]
I've thickened it up slightly, and will include it in release [v1.2.52](https://github.com/arallsopp/hass-hue-icons/releases/tag/v1.2.52).

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 437 custom icons has been driven by a community request just like yours, and stars help people find this repo.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by arallsopp** [comment]
Closing for now. Please reopen if you want a tweak or rework.

**Comment by dathosim** [comment]
Thanks a lot !
I understand for the cable 😉
