### ISSUE TITLE
Off version of hue:ceiling-square

### ISSUE THREAD

**Issue by m1ke-hub** [arallsopp/hass-hue-icons#232]
**Additional context**

I did not fill out the complete template, as the "on" version already exists under hue:ceiling-square

It would be phenomenal, if you could also add the "off" version.

**Comment by arallsopp** [comment]
Aiming at this. I'll stage it for the next release if it looks right to you.
<img width="396" alt="image" src="https://github.com/arallsopp/hass-hue-icons/assets/2462104/1c4362fb-ac0a-4b1e-8f5c-dfba261111d6">

**Comment by arallsopp** [comment]
This has been bundled into the latest release. Apologies for not calling you out in the release notes directly. I made one release and introduced a bug, added your icon, realised the bug, fixed it and released anew which meant you didn't get a mention. Thanks for the request. Let me know if you have any issues.

**Comment by m1ke-hub** [comment]
Thanks a lot and no worries brother.. I am very grateful for your work nonetheless!
