### ISSUE TITLE
Updating to 1.2.52 results in no icons

### ISSUE THREAD

**Issue by lwsrbrts** [arallsopp/hass-hue-icons#234]
**Describe the bug**
After updating to 1.2.52 there are no hue icons displayed anywhere in the dashboard(s) in Firefox.

**To Reproduce**
Update to 1.2.52 via HACS.
Reload as per HACS request.

Also attempted to:
- Clear cache
- Force reload any dashboard
- F12 developer tools and select to "Disable Cache" then reload dashboards.

None of which results in the icons being displayed.

**Expected behavior**
The icons to be displayed where configured in the existing dashboard.

**Screenshots**
No icons are displayed for any configuration that uses them.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 120.0.01

**Smartphone (please complete the following information):**

**Additional context**
Attempted loads of things before finally reverting to 1.2.51 which worked immediately after reloading via HACS prompt.

**Comment by arallsopp** [comment]
Eek. That doesn't sound good. Perhaps I missed a step. Let me check.

**Comment by lwsrbrts** [comment]
I didn't add screenshots but... this is using 1.2.51 (taken 30 seconds ago)
![image](https://github.com/arallsopp/hass-hue-icons/assets/15855642/408ad453-47e1-481e-ba40-72799ac1893d)

And, having just updated again, I see this...
![image](https://github.com/arallsopp/hass-hue-icons/assets/15855642/60b9edbe-0fc7-4f33-8f0e-516c44863590)

**Comment by arallsopp** [comment]
I may try to pull that last release until I can diagnose or recreate. Thanks for raising this.

**Comment by arallsopp** [comment]
I see it. Error in my javascript. I shall put on my "look at me, what an idiot" hat and wear it until fixed.

**Comment by arallsopp** [comment]
Hey, can you try [v1.2.53](https://github.com/arallsopp/hass-hue-icons/releases/tag/v1.2.53) and let me know if that resolves it for you?

**Comment by NicoMalm** [comment]
The icons are back with v1.2.53. Thanks!!!

**Comment by lwsrbrts** [comment]
Sorry, I got distracted with some new toys.

Ooh, flattery too!
![image](https://github.com/arallsopp/hass-hue-icons/assets/15855642/35610bdc-af20-4b3e-9cc1-1cef1eb9a1b9)

Thank you. All looks good to me on 1.2.53!

**Comment by arallsopp** [comment]
Thanks to you and @NicoMalm. Really appreciate you catching this.

**Comment by lwsrbrts** [comment]
As do we appreciate the work you've put in to this. Thanks for that!
