### ISSUE TITLE
I added hue-icons to the HA overview, and after a reboot they don't show up.

### ISSUE THREAD

**Issue by fribse** [arallsopp/hass-hue-icons#24]
**Describe the bug**
I've added quite a few HUE icons (they look great) to my HA lovelace.
In the device view the icons work, but in the panel overview they don't.

**To Reproduce**
1. Add Hue icon to panel
2. Reboot
3. Icons doesn't show

**Expected behavior**
I don't understand the limitation, I can add all sorts of other types of icons to the panel overview.

**Screenshots**

Missing icons from panel overview
![image](https://user-images.githubusercontent.com/13660621/128992780-1a03326b-b5d6-4ea7-86fc-9f46970b1a93.png)

Working inside a card:
![image](https://user-images.githubusercontent.com/13660621/128992518-1e1b8e3f-50f2-4e52-9801-a679f94ef34a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Browser Firefox
 - Version 90.0.2

**Comment by fribse** [comment]
Ok, this is really weird.
I went into to change them back.
Then it showed the icons:
![image](https://user-images.githubusercontent.com/13660621/128993605-f9bbe624-2645-4b5c-a1b8-d9004289daf6.png)
Going back out of editing, it's still showing the icons:
![image](https://user-images.githubusercontent.com/13660621/128993670-8f4bba54-3c9f-4fa1-9d71-6e7782d9dba6.png)
If I press F5, they are gone:
![image](https://user-images.githubusercontent.com/13660621/128993724-f486f994-5d5f-4321-975f-ed0e679d20cf.png)

**Comment by arallsopp** [comment]
Quick question: 

Did you perform the installation step to add the extra_module_url?

frontend:
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js

I've had the icons only show after clicking into different pages within Lovelace if this isn't done.

**Comment by fribse** [comment]
You are right, I didn't do that step, I installed it via HACS, and that apparently doesn't do anything correspondig.
Might be a good idea to modify the instructions a bit, so that part is also shown under HACS.
After I added that to the config, it's working!

**Comment by arallsopp** [comment]
Glad to hear. Yes, its a bit annoying that HACS doesn't let you make those changes as part of the installer. I did raise a [request](https://github.com/hacs/integration/issues/2123) about that, but its by design.
