### ISSUE TITLE
Group or ledstrip & bulb lamps

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#27]
hey can you also make icon from group ledstrip ?  & also of bulb lamps like this?![image](https://user-images.githubusercontent.com/60328474/129094685-a35209d0-7004-45e8-bd14-fc62ad9d1237.png)
Thank you!

**Comment by arallsopp** [comment]
A group of ledstrips sounds like a Hue type thing. I'll see if I can come up with something that works.

For the fixture, I'm not familiar with that model. Is it actually a hue lamp?

**Comment by arallsopp** [comment]
v.1.0.51 and up includes new groups for lightstrips, as horizontal (default) and vertical (-v). Good suggestion. Thanks for that @jrspowers.

| Icon | Name |
| :--- | :--- |
![hue:bulb-group-lightstrip](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-lightstrip.svg)| hue:bulb-group-lightstrip |
 ![hue:bulb-group-lightstrip-v](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-lightstrip-v.svg)| hue:bulb-group-lightstrip-v | 

The lamp you've linked looks to be a 10 inch / 25cm [IKEA Fado](https://www.ikea.com/us/en/p/fado-table-lamp-with-led-bulb-white-60416280/). Hass-hue-icons aims to provide additional vector icons for home assistant to model **Philips Hue bulbs and fixtures**, so I won't be modelling the Fado at this time.

Suggest you might look at mdi:checkbox-blank-circle, as that could get you close with the mdi icons bundled into Home Assistant.
![image](https://user-images.githubusercontent.com/2462104/129107830-8418e1df-381a-41ac-be2a-aacba73980bd.png)

**Comment by arallsopp** [comment]
Will close if no further feedback, as group lightstrip hopefully satisfies the actionable part of the original request.

**Comment by jrspowers** [comment]
ok top LED strip & no is a Hue lamp not the lamp itself but the lamp in it?  but understand that you're not going to do it, thanks in advance for making LED strip

**Comment by arallsopp** [comment]
Thanks for the request. Alongside #6, its people like you that drive this library forward and make it more useful to all of us.*

* even if I do reject some of the requests ;)


v.1.0.51 is up, so you can use your group lightstrips as soon as you update.

**Comment by jrspowers** [comment]
you're very welcome please help me out for these icons very nice project of yours & i'm going to use them tomorrow thanks
