### ISSUE TITLE
Philips hue play gradient lightstrip

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#28]
hey i have a question could you do this philips hue play gradient lightstrip like the picture would be very nice icon thanks in advance![image](https://user-images.githubusercontent.com/60328474/129109011-e6f326f3-085d-4570-8a5e-f925c82e97c7.jpeg)

**Comment by arallsopp** [comment]
Added variations for differing lightstrip installations into v.1.0.52 

| Icon | Name |
| :--- | :--- |
![hue:lightstrip-wrap](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lightstrip-wrap.svg)| hue:lightstrip-wrap |
![hue:gradient-lightstrip-wrap](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/gradient-lightstrip-wrap.svg)| hue:gradient-lightstrip-wrap |
![hue:lightstrip-tv](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lightstrip-tv.svg)| hue:lightstrip-tv |

**Comment by arallsopp** [comment]
Adding a hue:lightstrip-tv-alt as below, as not 100% on that hue:lightstrip-tv above:

![image](https://user-images.githubusercontent.com/2462104/129118306-928e48a8-ede2-44c1-85dd-f9c16961b39d.png)

**Comment by jrspowers** [comment]
thank you man thank you for making this icon
