### ISSUE TITLE
Group ledstrip & bulb sultan ?

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#32]
hello i have a question is it possible to make icon where ledstrip & bulb sultan can display as a group would be very nice should work thanks in advance

**Comment by arallsopp** [comment]
Yeah, i'll jump on that. Am a bit distracted at present, as have just been pointed at a repo that's been taking the icons I'm creating here and passing them off as their own work. I'm all for collaboration, and the home assistant community is all about sharing, but I'll admit to being a bit annoyed that the other repo isn't crediting me for my work, especially as they're just tracking along behind my release notes, but adding a paypal link for donations....

Hmmm...

**Comment by arallsopp** [comment]
This is what I'll be going for.

![image](https://user-images.githubusercontent.com/2462104/129452427-d654a278-0abd-405c-9901-53eb23dc3d2c.png)

**Comment by jrspowers** [comment]
amai that's really not nice no & looks very nice thanks man & I think you are very nice what you do and do you want to hear something doner for your work?

**Comment by arallsopp** [comment]
Added bulb-group-sultan-lightstrip

| Icon | Name | 
| :--- | :--- |
 | ![hue:bulb-group-sultan-lightstrip](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-sultan-lightstrip.svg)| hue:bulb-group-sultan-lightstrip |

**Comment by arallsopp** [comment]
@jrspowers I could do with a cheer up. Tell me something about your usage or share a screenshot of your dash? It'd be good to see the icons in use :)

**Comment by jrspowers** [comment]
here are some pictures of your icons in my dashboard word very nice use hear & work very well thank you man !![image](https://user-images.githubusercontent.com/60328474/129455295-fa928ed2-0aef-43ec-bfe1-5335743bf405.png)

![image](https://user-images.githubusercontent.com/60328474/129455301-8b3be888-270f-4ac2-9199-61168f22d92d.png)

![image](https://user-images.githubusercontent.com/60328474/129455304-c244d9b8-b59e-4821-95ab-8421c70585c2.png)

![image](https://user-images.githubusercontent.com/60328474/129455307-640f48d9-e3d5-4e23-bcf8-aa1210aaf354.png)

![image](https://user-images.githubusercontent.com/60328474/129455317-2e2a0228-ba98-4694-9c06-37c768b560cc.png)

**Comment by jrspowers** [comment]
I still have a question, could you also make an off version of the hue:bulb-group-sultan-lightstrip that I would like to use on photo 1 if everything turns out that there is a line through it and turns red?  Thanks in advance
