### ISSUE TITLE
Philips hue sync box

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#33]
hello can you make an icon of philips hue sync box would be very nice & handy & see photo for the box thanks in advance![image](https://user-images.githubusercontent.com/60328474/129449697-7edd8692-f35f-492f-a104-7a1ba225f110.jpeg)

**Comment by arallsopp** [comment]
Tricky, with it basically being a black rectangle.

I'm currently thinking I need to go for something that represents its purpose, more than its shape.

![image](https://user-images.githubusercontent.com/2462104/129458344-fd6bf983-d674-4875-9cad-b17cd20b319e.png)

**Comment by jrspowers** [comment]
it would be nice if you could get it ready like this box but that hdmi is already a nice solution

**Comment by arallsopp** [comment]
I'm trying.... bear with me :)

![image](https://user-images.githubusercontent.com/2462104/129461935-f5b85ce8-5b42-4c71-a8a4-92fa5b141699.png)

**Comment by jrspowers** [comment]
thanks looks really nice and be patient with you no problem!

**Comment by arallsopp** [comment]
They're in. Text is pretty small, but hopefully readable.

Feel free to re-open / comment with suggestions.

| Icon | Name |
| :--- | :--- | 
| ![hue:sync-box-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/sync-box-alt.svg)| hue:sync-box-alt | 
| ![hue:sync-box](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/sync-box.svg)| hue:sync-box |

**Comment by jrspowers** [comment]
thank you man & I will definitely do it if necessary
