### ISSUE TITLE
Philips Ledino

### ISSUE THREAD

**Issue by pascalwinters** [arallsopp/hass-hue-icons#36]
Is it possible to add an icon for Philips Ledino:

![075FE2B7-B83A-47BE-A979-B79AA9DA2E42](https://user-images.githubusercontent.com/69316923/129481541-1ebd45e1-6686-4bc9-b6cb-bc3cfed62335.jpeg)
![84EAE014-0DF8-45C8-A9B2-DBEAF51F9517](https://user-images.githubusercontent.com/69316923/129481542-4c8082ff-3233-4ec4-b2c9-8b0aa0b497ff.jpeg)
![B5EAB0A2-C5FF-4DF2-860E-A687C77E0CD7](https://user-images.githubusercontent.com/69316923/129481543-7149cff6-608a-478a-a5a4-15e4dfb7e470.jpeg)
![4F61FB63-8B2F-41AE-BB8E-502DC20AE0EC](https://user-images.githubusercontent.com/69316923/129481544-07653e61-f9e6-4e88-9340-ca3217b7c31b.jpeg)

**Comment by arallsopp** [comment]
Hey @pascalwinters. I appreciate the interest. I don't think this is a hue light, though, so it probably doesn't really belong in this repo? 

Its a pretty thing, mind.

**Comment by pascalwinters** [comment]
Hey @arallsopp, it isn't a hue light but a Philips. So I thought maybe it's interesting, but no problem.
