### ISSUE TITLE
Icon Request (Flourish)

### ISSUE THREAD

**Issue by davislp** [arallsopp/hass-hue-icons#44]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Flourish Table Lamp
https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-flourish-table-light/4090431U9

Be as specif
ic as you can, as Philips often seem to have product family names where multiple variants exist under the same description.

**Provide a URL that points to an image of this fixture/bulb**

https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-flourish-table-light/4090431U9

Preferably Philips' photography, as they use a consistent angle.

**Additional context**

Add any other context for your icon request here.

**Comment by arallsopp** [comment]
Will give it a go. It's not a hugely recognisable shape, but I'll do what I can. :)

**Comment by davislp** [comment]
Awesome. And, yeah, it is sort of just an oval now that you say it.

**Comment by arallsopp** [comment]
I'm going to base it on this, as it gives a profile at least.

![image](https://user-images.githubusercontent.com/2462104/131232506-d68133a5-93ec-4941-9bbe-81351676b087.png)

Also, there's a ceiling mounted version. Didn't know that!
![image](https://user-images.githubusercontent.com/2462104/131232498-bc30cd8f-5146-43ec-9c44-10c64d688345.png)

**Comment by davislp** [comment]
Sounds good. I didn't know there was a ceiling version either, but now I'm
getting ideas (expensive ideas).

**Comment by arallsopp** [comment]
Always the way... Sorry! :)

Do you think outline, or solid for the flourish? I've generally gone with outline, but unsure for this one. Could do both, I suppose.

![image](https://user-images.githubusercontent.com/2462104/131232598-c5a613b0-a846-48dd-8e84-7f63f2b873ed.png)

**Comment by arallsopp** [comment]
Ceiling version looks a bit flat like this. Might go 3D instead.

![image](https://user-images.githubusercontent.com/2462104/131232839-94d4731f-8922-4fdb-8bca-d16e5509790a.png)

**Comment by arallsopp** [comment]
Yeah, that's better.

![image](https://user-images.githubusercontent.com/2462104/131232932-4624d223-08e1-45f6-88f7-d6807aa17ffa.png)

**Comment by davislp** [comment]
I guess both, but I'll probably use the outline myself.

**Comment by arallsopp** [comment]
Coming up...

| Icon | Name |
| :--- | :--- | 
| ![hue:ceiling-flourish](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-flourish.svg)| hue:ceiling-flourish |
| ![hue:flourish](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/flourish.svg)| hue:flourish | ![hue:friends-of-hue-arke-round](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/friends-of-hue-arke-round.svg)| hue:friends-of-hue-arke-round |
| ![hue:flourish-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/flourish-alt.svg)| hue:flourish-alt |

**Comment by davislp** [comment]
Thank you!
