### ISSUE TITLE
Hue aura 

### ISSUE THREAD

**Issue by fjjfrank** [arallsopp/hass-hue-icons#46]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Be as specific as you can, as Philips often seem to have product family names where multiple variants exist under the same description.

**Provide a URL that points to an image of this fixture/bulb**

Preferably Philips' photography, as they use a consistent angle.

**Additional context**

Add any other context for your icon request here.

**Comment by fjjfrank** [comment]
https://nl.pinterest.com/pin/535365474430747901/

**Comment by arallsopp** [comment]
Is that actually a Hue lamp? I'd thought it was a Living Colours model, that maybe became the bloom?

![image](https://user-images.githubusercontent.com/2462104/131242480-03440c56-eb94-40e7-baaa-8e186fe39343.png)


| Icon | Name | 
| :--- | :--- |
| ![hue:bloom](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/bloom.svg)| hue:bloom | 

I'm trying to keep this repo solely for Hue presently. Might the bloom icon work for you?

**Comment by fjjfrank** [comment]
First thanks for your great icons mine ha looks greater now.
Yes it's a hue lamp I have got 2 of these 
But in the hue app there is also not a icon for so i thought I will give it a try to ask.
I also have now in ha the bloom icon for it

**Comment by arallsopp** [comment]
Here's my thinking then
![image](https://user-images.githubusercontent.com/2462104/131243294-3b849523-f517-455e-85f5-7a9141beb5df.png)

**Comment by fjjfrank** [comment]
That's looks great 
Maybe u can make a round spot in the middle of the circle

**Comment by arallsopp** [comment]
You know this light better than me, @fjjfrank  :)

Hope you find it useful, and thanks for helping improve hass-hue-icons. Please consider starring the repo to help bring it to others attention.

| Icon | Name | 
| :--- | :--- | 
| ![hue:aura](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/aura.svg)| hue:aura |

**Comment by fjjfrank** [comment]
Wow Yesss it's look great 
Thank u for this 
U are great
