### ISSUE TITLE
Icon Request for Muscari ceiling light

### ISSUE THREAD

**Issue by DigitalElise** [arallsopp/hass-hue-icons#50]
**What is the specific model of hue fixture/bulb that you want an icon for**
Muscari ceiling light

**Provide a URL that points to an image of this fixture/bulb**
https://www.philips-hue.com/en-au/p/hue-white-ambiance-muscari-ceiling-light/4503748C6

Thanks

**Comment by arallsopp** [comment]
Great suggestion.

Thanks, @DigitalElise 

Here it comes:
![image](https://user-images.githubusercontent.com/2462104/132346113-f8ed1a20-61e5-44c4-8d60-b720ee286d81.png)

**Comment by arallsopp** [comment]
Thanks again @DigitalElise.

It'll be in 1.0.79, coming soon:

| Icon | Name |
| :--- | :--- |
| ![hue:ceiling-muscari](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/ceiling-muscari.svg)| hue:ceiling-muscari|

**Comment by DigitalElise** [comment]
Amazing! I didn't expect it to be done so soon!

**Comment by arallsopp** [comment]
Ooh! There's a pendant version too. Not seen these in the UK at all. Will add that too.

![image](https://user-images.githubusercontent.com/2462104/132374858-6113cf1c-527d-42de-a93a-deb72db4cc5b.png)

| Icon | Name |
| :--- | :--- |
| ![hue:pendant-muscari](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-muscari.svg)| hue:pendant-muscari|
