### ISSUE TITLE
hue Pendant lamp cher 4076131P6

### ISSUE THREAD

**Issue by jockeb76** [arallsopp/hass-hue-icons#51]
Hello!
I would be nice if you could add hue Pendant lamp cher 4076131P6 to the Icon collection.

If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**
hue Pendant lamp cher 4076131P6
Be as specific as you can, as Philips often seem to have product family names where multiple variants exist under the same description.

**Provide a URL that points to an image of this fixture/bulb**
https://www.philips-hue.com/sv-se/p/hue-white-ambiance-cher-pendel/4076131P6
Preferably Philips' photography, as they use a consistent angle.

**Additional context**

Add any other context for your icon request here.

**Comment by arallsopp** [comment]
Will be on it tonight. Thanks for the suggestion, @jockeb76

**Comment by arallsopp** [comment]
Coming up:
![image](https://user-images.githubusercontent.com/2462104/132404468-ec80e634-2190-4630-8bf3-01f4c9032c04.png)

**Comment by arallsopp** [comment]
Thanks again, @jockeb76. Coming up in version 1.0.81.

| Icon | Name |
| :--- | :--- |
| ![hue:pendant-cher](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pendant-cher.svg)| hue:pendant-cher|
