### ISSUE TITLE
Icon request: Adore mirror

### ISSUE THREAD

**Issue by iudex-** [arallsopp/hass-hue-icons#53]
**What is the specific model of hue fixture/bulb that you want an icon for**
Adore Lighted Vanity Mirror 

**Provide a URL that points to an image of this fixture/bulb**
https://www.philips-hue.com/en-us/p/hue-white-ambiance-adore-lighted-vanity-mirror/3435831U7
![b9778d95b37f435bbc3fad75008d8bab](https://user-images.githubusercontent.com/56843/132571708-1ca4ccdc-6929-48ad-a77d-e0878e7ead0c.jpeg)

**Additional context**
>Especially designed for: Bathroom 

While the "light ring" around the mirror appears filled in Philipps images it's actually not.
The round mirror is just sitting in the middle of an empty "shell"
See: https://www.youtube.com/watch?v=IPhy_RSsgNY
![Untitled](https://user-images.githubusercontent.com/56843/132572460-06f8f999-b801-45be-8f05-5538d810c5ef.png)

**Comment by arallsopp** [comment]
Interesting insight. Yeah, I'll have a go at that. Will endeavour to make it more than just a circle 😁

**Comment by arallsopp** [comment]
Hey @iudex. 

Given your choice of the images below (option 1, reference photo, option 2, option 3) what's your preference?
I'm thinking option 2.
![image](https://user-images.githubusercontent.com/2462104/132589458-e40c527e-66a2-44b4-badc-2460a2a7bae4.png)

**Comment by iudex-** [comment]
oh wow, what is this turnaround time? :exploding_head: 

yeah, options 2 feels right.
The filled center also helps to distinguish it from `hue:daylo-wall` and `hue:sana`

Thank you so much! :blush:

**Comment by arallsopp** [comment]
No problem, @iudex-. Always good to give back to the community. Your icon is coming up in v.1.0.82. 

| Icon | Name |
| :--- | :--- |
| ![hue:adore-mirror](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/adore-mirror.svg)| hue:adore-mirror|

**Comment by arallsopp** [comment]
Oh, @iudex- 

You were totally right about that sana lamp, btw. I’ve just reworked it (keeping old version as -alt suffix). Never was quite happy with it, and your comment gave me the push to sort it out :)

| Icon | Name |
| :--- | :--- |
| ![hue:sana](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/sana.svg)| hue:sana| |
| ![hue:sana-alt](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/sana-alt.svg)| hue:sana-alt|
