### ISSUE TITLE
Group lights

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#59]
hello can you make a group of the bulb spot & bulb sultan as well on as the off version would be very nice & i'm glad you are back good luck further you are doing very well !

**Comment by arallsopp** [comment]
Howdo @jrspowers. Thanks for waiting for me. These are coming up in the next release. 

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-sultan-spot](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-sultan-spot.svg)| hue:bulb-group-sultan-spot|
| ![hue:bulb-group-sultan-spot-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-sultan-spot-off.svg)| hue:bulb-group-sultan-spot-off|

**Comment by jrspowers** [comment]
thanks for adding this lamps group is great

**Comment by arallsopp** [comment]
No prob. Enjoy.
