### ISSUE TITLE
Hue centris 2 spot

### ISSUE THREAD

**Issue by jrspowers** [arallsopp/hass-hue-icons#6]
it is about this lamp would be very nice if he can add it?

[Hue Certris 2 spot](https://www.philips-hue.com/nl-be/p/hue-white-and-color-ambiance-centris--2-lichts-plafondlamp/5061030P7) 

here is a picture of the icon ?
![C0003F9F-F700-4FF3-B6A3-2D9146A8A2C5](https://user-images.githubusercontent.com/60328474/125867726-11a7cfd0-9b98-421c-9207-b530f8a6284d.jpeg)

**Comment by arallsopp** [comment]
Well done finding that icon. I've been looking at the centris, but they're just a jumble of lines in the stock photography making it really hard to render out. Leave it with me.

**Comment by arallsopp** [comment]
Here you go,  @jrspowers. That'll be in v1.0.21 and up.

![image](https://user-images.githubusercontent.com/2462104/125935605-9fea1ab4-5deb-485a-8607-02e4046f99a5.png)

**Comment by arallsopp** [comment]
I've marked this as closed for now, but if you need the **two** spot version to show as an icon, feel free to re-open. I'll have to think about how to draw it, as it'll get awful busy if I start trying to put multiple spots in there. Probably why Philips only show the one :)

**Comment by jrspowers** [comment]
hello this is the right icons that is also used in the hue app so this one is very great thanks man

**Comment by arallsopp** [comment]
(Doesn't stop me playing though, @jrspowers  :))
![image](https://user-images.githubusercontent.com/2462104/126014203-c99e2a96-cbd8-4d8c-ba96-ea42df43b7f4.png)

**Comment by jrspowers** [comment]
you are great man thanks for making this very nicely done will install it immediately when it is there 😊

**Comment by arallsopp** [comment]
Thanks for your patience, @jrspowers . I had to shorten the arm a little, and thicken up the weight so that it worked at screen resolution. Release 1.0.24 is on the way.

![image](https://user-images.githubusercontent.com/2462104/126016338-d52ee38d-48cc-4b6a-96de-199af1c69b5b.png)

**Comment by jrspowers** [comment]
no problem you are really great man thanks for bringing this in order & going to install the update immediately thanks man😊

**Comment by arallsopp** [comment]
My pleasure. I ran off a centris-three whilst I was there. Its fairly heavy looking so think I'll stop there! :)

![image](https://user-images.githubusercontent.com/2462104/126017798-9d21dd5a-5a7b-4d30-a5ab-ee3298faa9b0.png)

Thanks for the interest.

**Comment by jrspowers** [comment]
yes that is very nice & yes also think that 4 is too busy so perfectly made 😊

**Comment by jrspowers** [comment]
hello i have problem with the icon hue:centris-two that doesn't work shows no icon when set up even after restarting ha ?  can you fix this?  thanks in advance!

**Comment by arallsopp** [comment]
It's likely to be your browser cache. A hard refresh will normally do it. If you open the developer console in your browser you should have a message telling which version you're running. CTRL and F5 on windows, or CMD+R on a Mac. Sometimes you need to edit the entity again just to force it to read. If hacs is showing you're up to date, you're seeing the same version I'm using, and I've just checked the icon is working on my phone. 

 ![image](https://user-images.githubusercontent.com/2462104/126046391-17c0c1ac-98aa-4594-8d95-35f8de4f4b1c.png)

**Comment by jrspowers** [comment]
on my mobile it works very well but on laptop not so well but I often suffer from it so will try with F5 then it will work thanks in advance for the nice development of icons!

**Comment by arallsopp** [comment]
Thanks. Sorry if I came across as dismissive.

**Comment by jrspowers** [comment]
no, definitely not very good explanation
