### ISSUE TITLE
Icon request: Dual Play Bar vertical

### ISSUE THREAD

**Issue by Phreet** [arallsopp/hass-hue-icons#60]
**What is the specific model of hue fixture/bulb that you want an icon for**

Hue Play Bar (Double Pack)

**Provide a URL that points to an image of this fixture/bulb**

![image](https://user-images.githubusercontent.com/29259815/133670288-b00c60de-c76b-42a0-a063-bb4dd30b26f0.png)

**Additional context**

Many people use both Hue Play Bars in vertical position next to monitors - so I'd imagine to use your already available hue:play-bar-v and add it mirrored around y-axis.

**Comment by arallsopp** [comment]
Thanks, yes, that's a good idea. Wonder whether they'd look better facing the same way, outwards, or inwards. I'll post back here today with a few options rendered.

**Comment by arallsopp** [comment]
@Phreet: Here are the choices:
![image](https://user-images.githubusercontent.com/2462104/133739261-cdf912e0-443c-434c-a9bd-025d4a70a057.png)

- Option 1 is more in keeping with other icons (eg: the other play bar images ![image](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/play-bar-two.svg).
- Option 2 is how you imagined it.
- Option 3 is closer to how mine are actually installed. 

Could just do all three, I suppose :) Any preference?

**Comment by arallsopp** [comment]
Thanks for the star, @Phreet. 

Here are your icons, all in release v.1.0.86.

| Icon | Name |
| :--- | :--- |
| ![hue:play-bar-v-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/play-bar-v-two.svg)| hue:play-bar-v-two|
| ![hue:play-bar-v-two-out](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/play-bar-v-two-out.svg)| hue:play-bar-v-two-out|
| ![hue:play-bar-v-two-in](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/play-bar-v-two-in.svg)| hue:play-bar-v-two-in|

**Comment by arallsopp** [comment]
That's better. Reworked the single one too.

| Icon | Name |
| :--- | :--- |
| ![hue:play-bar-v](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/play-bar-v.svg)| hue:play-bar-v|
| ![hue:play-bar-v-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/play-bar-v-two.svg)| hue:play-bar-v-two|
| ![hue:play-bar-v-two-out](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/play-bar-v-two-out.svg)| hue:play-bar-v-two-out|
| ![hue:play-bar-v-two-in](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/play-bar-v-two-in.svg)| hue:play-bar-v-two-in|

**Comment by Phreet** [comment]
@arallsopp wow - thanks a lot for the lightning fast realization and merge! icons look great and I really like your tweak in in and out angle of the verti bars 👍

**Comment by arallsopp** [comment]
No problem. Glad to be able to help.
