### ISSUE TITLE
Philips Hue Impress 17432

### ISSUE THREAD

**Issue by Bolgath** [arallsopp/hass-hue-icons#65]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Philips Hue Impress 17432

**Provide a URL that points to an image of this fixture/bulb**

https://www.philips-hue.com/sv-se/p/hue-white-and-color-ambiance-impress-stolplampa-for-utomhusbruk/1743230P7

**Additional context**

Add any other context for your icon request here.

**Comment by arallsopp** [comment]
Nice one. I may have to make it a bit shorter to fit a square, but leave it with me 😃

**Comment by arallsopp** [comment]
OK. So here's my suggestion for the two impress pillars. Obviously I've compressed the geometry a little to make them fit in a square icon, but there's hopefully still enough difference between them to tell this one apart from request #66

![image](https://user-images.githubusercontent.com/2462104/134765729-4b79a90a-8315-4bb2-94f1-8e21eb14a7ee.png)

**Comment by arallsopp** [comment]
Added in v.1.0.89. Thanks again, @Bolgath for the suggestion.

| Icon | Name |
| :--- | :--- |
| ![hue:pillar-impress](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pillar-impress.svg)| hue:pillar-impress|
| ![hue:pillar-impress-short](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/pillar-impress-short.svg)| hue:pillar-impress-short|
