### ISSUE TITLE
Hue Lilly

### ISSUE THREAD

**Issue by jayegles** [arallsopp/hass-hue-icons#71]
Please add Hue Lilly and Lilly Group

Lilly: https://image.migros.ch/fm-xl/cac1b0b1ad4de0f2b9a2f057349e2a346fda2801/philips-hue-hue-lilly-gartenspot.jpg 
Lilly Group: https://www.assets.signify.com/is/image/PhilipsLighting/943bf0ea771648f68b35ac2b00a6a485

Thanks
Jakob

**Comment by arallsopp** [comment]
Hey. Good call. I've been tending to use hue:floor-spot (![hue:floor-spot](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/svgs/floor-spot.svg)) but these do really deserve an icon of their own. Leave it with me.

**Comment by arallsopp** [comment]
@jayegles: What do you think? With the cut out where the arm mounts, or without?

![image](https://user-images.githubusercontent.com/2462104/135126986-0ce72c8e-1a90-465b-8dfc-bcfef1026b3a.png)

**Comment by arallsopp** [comment]
The multi one will definitely need to omit the cutout, else it'll get way too busy. Its still quite intense and hard to read.
![image](https://user-images.githubusercontent.com/2462104/135129570-2ab13e47-298d-407f-b8db-1bd1a9d8b797.png)

**Comment by arallsopp** [comment]
Other bulb groups I've created use two lamps. Would that be acceptable?
![image](https://user-images.githubusercontent.com/2462104/135130022-25d15d41-61ac-4d54-a2ac-b90e5aa64518.png)

**Comment by jayegles** [comment]
Hey,

thanks for the quick replies :-)

The group of two lamps ist looking great and is really fine for me.
The single lamp ist looking better without cutout in my opinion.

Andy Allsopp ***@***.***> schrieb am Di., 28. Sept. 2021,
18:44:

**Comment by arallsopp** [comment]
Thanks for the suggestion, @jayegles.

Your icons are coming up in v1.0.93. As always, if you'd like to help others find this repo, please consider giving it a star. Thanks.

 | Icon | Name |
| :--- | :--- |
| ![hue:lilly](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lilly.svg)| hue:lilly|
| ![hue:lilly-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lilly-two.svg)| hue:lilly-two|

**Comment by priiduonu** [comment]
The official name is **lily** not lilly.

**Comment by arallsopp** [comment]
Ah. I'd better rename that this morning then before too many are using it. Thanks!

**Comment by arallsopp** [comment]
Ok. That's fixed in 1.0.94. Thanks again @priiduonu for the spot.

@jayegles: That's a breaking change. If you're using either of the 'lilly' icons, you'll need to correct the spellings to 'lily' before the icons show up after you update.

| Icon | Name | Old Name |
| :--- | :--- | :--- |
| ![hue:lily](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lily.svg)| hue:lily| hue:lilly|
| ![hue:lily-two](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lily-two.svg)| hue:lily-two| hue:lilly-two |
