### ISSUE TITLE
ceiling

### ISSUE THREAD

**Issue by Jydske** [arallsopp/hass-hue-icons#73]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Be as specific as you can, as Philips often seem to have product family names where multiple variants exist under the same description.

**Provide a URL that points to an image of this fixture/bulb**

Preferably Philips' photography, as they use a consistent angle.

**Additional context**

Add any other context for your icon request here.

**Comment by arallsopp** [comment]
Hey @Jydske.

do you have any more information on that icon request? All I’m seeing is the word “Ceiling” and that isn’t really enough for me to go on. A url pointing to a Philips hue light is about the minimum I’d need to advance this. 

Cheers!

**Comment by arallsopp** [comment]
@Jydske: I'll leave this open a while, in case there is further information forthcoming. If nothing back within a week of opening, I'll be closing this ticket. You're free to open another if you subsequently find the detail you're missing. Cheers!

**Comment by arallsopp** [comment]
Closing for now. @Jydske: feel free to open another with detail.
