### ISSUE TITLE
Icon Request Philips Hue Phoenix

### ISSUE THREAD

**Issue by viDU85** [arallsopp/hass-hue-icons#75]
- Philips Hue Phoenix Pendant Light
- Philips Hue Phoenix Plafond Lamp

**Philips Hue Phoenix Pendant Light:**
https://www.tulampara.es/media/product/32791/1000x1000/philips-hue-ambiance-white-phoenix-lampara-colgante-8718696126615-0.jpg
https://www.tulampara.es/media/product/32791/1000x1000/philips-hue-ambiance-white-phoenix-lampara-colgante-8718696126615-4.jpg
https://www.tulampara.es/media/product/32791/1000x1000/philips-hue-ambiance-white-phoenix-lampara-colgante-8718696126615-5.jpg
https://www.lampamania.es/philips-31152-31-ph-lampara-colgante-regulable-hue-phoenix-2xled-9w-230v-img-p1420_4-fd-11.jpg

**Philips Hue Phoenix Plafond Lamp**
https://www.assets.signify.com/is/image/PhilipsLighting/68100cef4192460e8715a9b900a4a422?wid=960&hei=720&qlt=82
https://www.assets.signify.com/is/image/PhilipsLighting/8cec2e1eb8bf4e2b94fda9d100f8e04b?wid=960&hei=720&qlt=82

**Video:**
https://www.assets.lighting.philips.com/is/content/PhilipsLighting/003031782ef3496ebab9a9d000edda7c

**Comment by viDU85** [comment]
thanks!

**Comment by arallsopp** [comment]
Making progress...
![image](https://user-images.githubusercontent.com/2462104/136619671-9137bd9f-fef3-4e65-8240-bdfa88e495f6.png)

**Comment by arallsopp** [comment]
Ok. The semi flush version is pretty much there. Now onto the pendant.

![image](https://user-images.githubusercontent.com/2462104/136621239-b6d01289-5054-467d-b967-f38f9f2f1782.png)

**Comment by arallsopp** [comment]
Here come the reworks. There'll be another release shortly.

![image](https://user-images.githubusercontent.com/2462104/136651146-d6a18c20-290b-479c-b72f-87bff65b6d0a.png)

**Comment by arallsopp** [comment]
Ok. That's all in v.1.0.98. I've added phoenix-table and reworked phoenix-semiflush to match. The old semiflush has become phoenix-plafond, just incase you wanted to retain it @viDU85.


| Icon | Name |
| :--- | :--- |
| ![hue:phoenix-table](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/phoenix-table.svg)| hue:phoenix-table|
| ![hue:phoenix-semiflush](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/phoenix-semiflush.svg)| hue:phoenix-semiflush|
| ![hue:phoenix-pendant](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/phoenix-pendant.svg)| hue:phoenix-pendant|

| Icon | Name |
| :--- | :--- |
| ![hue:phoenix-plafond](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/phoenix-plafond.svg)| hue:phoenix-plafond|
