### ISSUE TITLE
Icon for Hue Being (ceiling mounted version of Hue pendant-being)

### ISSUE THREAD

**Issue by defisit** [arallsopp/hass-hue-icons#82]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Hue Being

Be as specific as you can, as Philips often seem to have product family names where multiple variants exist under the same description.

**Provide a URL that points to an image of this fixture/bulb**

https://www.philips-hue.com/nl-be/p/hue-white-ambiance-being-plafondlamp/3261048P6

Preferably Philips' photography, as they use a consistent angle.

**Additional context**

Comes in three colours. White, Aluminium and Black

Add any other context for your icon request here.

**Comment by arallsopp** [comment]
All done, @defisit. Its in release [1.0.100](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.0.100). 

If you'd like to help others discover this repo, please consider giving it a free star. The more eyes on, the more suggestions we get for better icons. Can't believe we've already got 158 custom drawn icons in! 🥇
