### ISSUE TITLE
icons sometimes do not appear when opening a page

### ISSUE THREAD

**Issue by Dilkins85** [arallsopp/hass-hue-icons#85]
**Describe the bug**
when opening a page, sometimes icons do not appear, sometimes reloading the page helps, the phone has the same history

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arallsopp** [comment]
@mstefany: that rework is now part of release [v1.1.2](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.2). If using it with core-2021.11.0 or greater, you can also use an icon picker to select hue icons. By removing support for the very old HA versions, you should either get the icons and no picker support (if HA reports a version prior to 2021.11.0) or the icons and picker support as below:

![image](https://user-images.githubusercontent.com/2462104/140232919-11ba7108-c0a9-41eb-9d40-de9fc8d8066d.png)

I can no longer recreate the issue, so am moving to close. Please re-open if you encounter any issues.

**Comment by TheJulianJES** [comment]
I think I have the same issue with Hass Hue Icons v1.1.10. I tried Home Assistant DEV build 2021.11.14 and 2021.11.24. The icons will load if the pages are switched. However, randomly they won't load on the initial page Home Assistant opens.

(Tried with iOS 15.1.1 and Chrome v96)

**Comment by arallsopp** [comment]
Hey there @TheJulianJES 

Did you take the following step at install:

Add the following to your configuration.yaml, save and restart HA.
frontend:
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js

**Comment by TheJulianJES** [comment]
Uh, thanks @arallsopp! That fixed the issue.

I somehow missed that in the README when installing via HACS.
(I guess I expected the icons to not work at all when something isn't present in the config).

So thanks again and sorry for the false alarm.

**Comment by arallsopp** [comment]
No problem. Glad we were able to resolve it quickly. Enjoy!
