### ISSUE TITLE
Icon Request [light bulb string]

### ISSUE THREAD

**Issue by thijselblaso** [arallsopp/hass-hue-icons#91]
Hi,

I use a Hue switch with a light bulb string in the garden. I really like to have an icon like the light bulb string from the picture below.

![lichtsnoer-voor-buiten-van-37-meter-met-80-extra-w](https://user-images.githubusercontent.com/38098396/140062743-a2053ce2-e270-46c8-a793-bab8ce5fe729.jpeg)

**Comment by arallsopp** [comment]
Howdo.

That's not really a hue light, so not sure it'd fit in this repo. I could do an inverted pair of filament bulbs, perhaps, or maybe mdi:string-lights is already close enough to what you have in mind?

![image](https://user-images.githubusercontent.com/2462104/140063550-0f02de6a-0536-487f-8ebc-f0f032c1bf3e.png)

**Comment by thijselblaso** [comment]
Thanks, I understand! If you have time, the filament bulb string would look very nice! For now, I use the mdi:string-lights. Thanks again for the great work!

**Comment by arallsopp** [comment]
I'm experimenting with a bulb-group-filament alternative, that would show two filament bulbs hanging *downwards*. Not sure there's room for three, but the two might well suit what you have in mind.

![image](https://user-images.githubusercontent.com/2462104/140301045-8c464192-4352-444c-8134-b5c1e3e90217.png)

I can see why the hue icons generally have the bulbs going up the other way. These ones look like, ahem, baubles.

**Comment by arallsopp** [comment]
Thanks @thijselblaso . It'll be in the next release [v.1.1.3](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.3).

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-filament-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-filament-hung.svg)| hue:bulb-group-filament-hung|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 162 custom icons has been driven by a community request just like yours.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
