### ISSUE TITLE
Hue icons in icon picker not showing up.

### ISSUE THREAD

**Issue by heinoskov** [arallsopp/hass-hue-icons#92]
**Describe the bug**
After following the release party today, Frenck showed the new icon picker with Hue icons in it. I followed the HACs installation method of Hass-hue-icons. Added the Frontend: part in the configuration.yaml... Rebooted Home Assistant and also reloaded and flushed the browser cache.

I can manually use the Hue Icons - but they are not showing up in the new icon picker.

Is there anything else to be done besides whats noted in the documentation under troubleshooting section.

Thanks in advance :-)

**Comment by arallsopp** [comment]
Howdo. I'm travelling at the moment, but did you install the hass hue icons beta release? What version of HA core are you using?

**Comment by arallsopp** [comment]
Ooh. It's live. Let me make a new release! Sorry!

**Comment by heinoskov** [comment]
Using latest version of Home Assistant - just released today

**Comment by arallsopp** [comment]
Got you! I see it. i've just tested new release [v1.1.2](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.2) against core-2021.11.0 and the picker supports the hue icons.

![image](https://user-images.githubusercontent.com/2462104/140232919-11ba7108-c0a9-41eb-9d40-de9fc8d8066d.png)

**Comment by heinoskov** [comment]
Working - Thanks :-)

**Comment by arallsopp** [comment]
Brilliant. Great to know, @heinoskov. Thanks for confirming.  

Please consider starring this repository if you'd like to help others discover it. Our moment of fame in the launch party won't last forever, and there are many more people who might benefit from hass-hue-icons.

**Comment by heinoskov** [comment]
Of course - done :-)
