### ISSUE TITLE
Icon Request [name of fixture]

### ISSUE THREAD

**Issue by billyat** [arallsopp/hass-hue-icons#93]
**What is the specific model of hue fixture/bulb that you want an icon for**

A group version of the existing hue:bloom icon would be nice. I have two which I operate as a group as well as individually.

**Provide a URL that points to an image of this fixture/bulb**

The existing hue:bloom icon

**Additional context**

Thank you very much for providing this integration. It is much appreciated.

**Comment by arallsopp** [comment]
That's fair. Ok. Will look to this overnight.

**Comment by arallsopp** [comment]
Howdo @billyat. Would they work arranged like this?

![image](https://user-images.githubusercontent.com/2462104/140407500-d1ec7a87-aea6-4263-afec-73fe3ad1f546.png)

**Comment by arallsopp** [comment]
Thanks for the suggestion @billyat . Assuming you're happy with the above, it'll be in release [v.1.1.4](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.4).

| Icon | Name |
| :--- | :--- |
| ![hue:bloom-group](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bloom-group.svg)| hue:bloom-group|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 163 custom icons has been driven by a community request just like yours.

### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by billyat** [comment]
Excellent, thanks very much for adding that. Sent from Mail for Windows From: Andy AllsoppSent: 04 November 2021 19:43To: arallsopp/hass-hue-iconsCc: billyat; MentionSubject: Re: [arallsopp/hass-hue-icons] Icon Request [name of fixture] (Issue #93) Thanks for the suggestion @billyat . Assuming you're happy with the above, it'll be in release v.1.1.4.IconNamehue:bloom-groupWant to help the community?If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 163 custom icons has been driven by a community request just like yours.Want to get involved?Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the forum thread?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
