### ISSUE TITLE
Icon request: A group of philips hue go

### ISSUE THREAD

**Issue by warbringer** [arallsopp/hass-hue-icons#94]
**What is the specific model of hue fixture/bulb that you want an icon for**
Hue Go

**Provide a URL that points to an image of this fixture/bulb**
![](https://www.signify.com/b-dam/signify/en-us/blog/posts/innovation/2019/new-philips-hue-smart-lighting-products/Hue_5_BL.jpg)

**Additional context**
Can you do the same for the hue:go as you did for hue:bloom to hue:bloom-group ?

**Comment by arallsopp** [comment]
Yep. I can move on that. Back soon!

**Comment by arallsopp** [comment]
Here's the proposal. Look right to you, @warbringer?

![image](https://user-images.githubusercontent.com/2462104/140497614-ab30457d-ca23-4bfc-8cb6-6c60bbf7c559.png)

**Comment by arallsopp** [comment]
Assuming you're happy with the images, it'll be in the next release [v.1.1.6](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.6).

| Icon | Name |
| :--- | :--- |
| ![hue:go-group](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/go-group.svg)| hue:go-group|


### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 164 custom icons has been driven by a community request just like yours.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
