### ISSUE TITLE
Icon Request  Off States

### ISSUE THREAD

**Issue by capandcamera** [arallsopp/hass-hue-icons#96]
Hello, 

Is there any possibility to get an off state icon for each?

Similar to mdi:lightbulb-spot and mdi:lightbulb-spot-off

This will allow users that use icons per states to show whether it is on or off using a different icon.

Thanks,

**Comment by arallsopp** [comment]
Howdo. For every custom bulb, or is there a particular one you have in mind?

**Comment by capandcamera** [comment]
Hi, 

I appreciate there is a lot of work involved in doing them all.
The key ones for my personal use-case are:

hue:bulb-classic
hue:go
hue:bulb-spot
hue:bulb-sultan
hue:floor-lantern
hue:lightstrip
hue:lightstrip-tv

Thank you

**Comment by arallsopp** [comment]
Ok. I'll try to run something up. Some of those icons are quite busy to add a bar through, but it should be doable.

**Comment by arallsopp** [comment]
Well that's going to be tricky. The standard off slash confuses the go icon. Wonder if I should put it the other way for this one.
![image](https://user-images.githubusercontent.com/2462104/141023186-11317cd0-de6b-4b07-8b1a-53df3c18ac19.png)
vs
![image](https://user-images.githubusercontent.com/2462104/141023317-8a74680c-a4dc-43bf-be65-be14bdab09d3.png)

I think I'll have to go with the standard top left to bottom right, as I imagine just one facing the other way will be weird.

**Comment by arallsopp** [comment]
Howdo Josh.

These are coming up in release [v.1.1.8](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.8). Let me know if you need any others, and I'll try to accommodate. Hue go is the only one that's tricky I think. If you prefer the alternate angle slash, let me know and I'll add that as an 'alt' version.

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-classic-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-classic-off.svg)| hue:bulb-classic-off|
| ![hue:go-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/go-off.svg)| hue:go-off|
| ![hue:bulb-spot-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-spot-off.svg)| hue:bulb-spot-off|
| ![hue:bulb-sultan-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-sultan-off.svg)| hue:bulb-sultan-off|
| ![hue:floor-lantern-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/floor-lantern-off.svg)| hue:floor-lantern-off|
| ![hue:lightstrip-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lightstrip-off.svg)| hue:lightstrip-off|
| ![hue:go-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/go-off.svg)| hue:go-off|
| ![hue:lightstrip-tv-off](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/lightstrip-tv-off.svg)| hue:lightstrip-tv-off|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 174 custom icons has been driven by a community request just like yours.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
