### ISSUE TITLE
[Icon Request] hanging version of hue:bulb-filament

### ISSUE THREAD

**Issue by warbringer** [arallsopp/hass-hue-icons#97]
**What is the specific model of hue fixture/bulb that you want an icon for**
Hue Filament bulb

**Additional context**
There an "upright" version of hue:bulb-filament and there's a group version of the hanging filament bulb but not a version of a single, hanging filament bulb. Can we get a hanging version of hue:bulb-filament?

**Comment by arallsopp** [comment]
Sure thing. Makes sense. Will get it back overnight as travelling presently.

**Comment by arallsopp** [comment]
Thanks again @warbringer. Its in release [v.1.1.9](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.9).

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-filament-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-filament-hung.svg)| hue:bulb-filament-hung|

### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 175 custom icons has been driven by a community request just like yours.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
