### ISSUE TITLE
v.1.1.9 keeps "looping" as update in HACS

### ISSUE THREAD

**Issue by bafplus** [arallsopp/hass-hue-icons#98]
**Describe the bug**
v.1.1.9 keeps hanging as pending update even after updating it. Its an endless loop now in HACS

**To Reproduce**
update from v.1.1.8 to v.1.1.9

**Desktop (please complete the following information):**
 - OS: Proxmox VM (probablt debian)
 - Browser [chrome
 - HA version 2021.11.3
 - HACS version 1.17.0

**Comment by viking-one** [comment]
![image](https://user-images.githubusercontent.com/74933120/141658104-7aa4b94e-d050-40de-ba10-3dd2b54dfacf.png)

**Comment by viking-one** [comment]
New verison of HACS just released (1.17.1), fixes the issue.

**Comment by arallsopp** [comment]
> New verison of HACS (1.17.1) just released, fixes the issue.

Well done. Thanks. Was wondering what I'd done! :)

**Comment by bafplus** [comment]
Great works! Thanks!

**Comment by arallsopp** [comment]
Closing now with thanks to @viking-one for the workaround.
