### ISSUE TITLE
Hue Bulb Classic Hung

### ISSUE THREAD

**Issue by bryeartem** [arallsopp/hass-hue-icons#99]
It is for hue classic bulbs, but for example my basement lights are just "classic" bulbs in a ceiling mounted socket fixture.
I was hoping you could just add a "hung" variation as well as a "group-hung" of the classic-bulb...I see you have it for some of the other bulbs already.   so it would just be the one you already have flipped upside down, and one with multiple... 

Thank you for your time and effort... It really makes my HA pages look so much nicer!!

**Comment by arallsopp** [comment]
Sounds fair. On it!

**Comment by arallsopp** [comment]
Classic is easy, enough.

![image](https://user-images.githubusercontent.com/2462104/142288193-dfb91fb4-66ed-4e41-a46a-aed75155f1d4.png)

For group hung, there's only hue:bulb-classic and hue:bulb-group (which uses sultan bulbs). I guess I'll need to create a new bulb-group-classic and bulb-group-classic-hung?

**Comment by bryeartem** [comment]
That’s what I was hoping for, just like the other group ones but upside down with the classic bulb.   Thanks again!  It makes such a difference in the interface when the icons look like the bulb you are looking for.

**Comment by arallsopp** [comment]
Bulb group classic will look like this, with hung being the inverted version. Does that cover off what you need?

![image](https://user-images.githubusercontent.com/2462104/142289426-cfea5aeb-02c0-4551-afeb-7ce1354daf5a.png)

**Comment by bryeartem** [comment]
Yes that is absolutely perfect!

**Comment by arallsopp** [comment]
Thanks for the suggestion, @bryeartem. Give me a few minutes to release it, and it'll be in [v.1.1.10](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.10).


| Icon | Name |
| :--- | :--- |
| ![hue:bulb-group-classic](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic.svg)| hue:bulb-group-classic|
| ![hue:bulb-classic-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-classic-hung.svg)| hue:bulb-classic-hung|
| ![hue:bulb-group-classic-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-hung.svg)| hue:bulb-group-classic-hung|



### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 178 custom icons has been driven by a community request just like yours.
### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?

**Comment by bryeartem** [comment]
Not sure if I did something wrong, (I am same guy in community forum that mentioned HACS saying this wasn't loaded properly no matter what I do, but it still works).. but I am not getting the new icons, and I do not see them in hass-hue-icons.js so I am not sure if that is why or if it is still related to my install issues.  Any suggestions?

**Comment by arallsopp** [comment]
@bryeartem: Excuse me. I had a momentary brain lapse and forgot to include them in the javascript. That was entirely my fault. Then I missed your message. Apologies. It'll be up tonight!

**Comment by arallsopp** [comment]
Apologies for the delay. Your icons have been bundled into release [v.1.1.11](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.1.11), which will work far better than my forgetting to do this entirely in v.1.1.10 😞 

| Icon | Name |
| :--- | :--- |
| ![hue:bulb-classic-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-classic-hung.svg)| hue:bulb-classic-hung|
| ![hue:bulb-group-classic](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic.svg)| hue:bulb-group-classic|
| ![hue:bulb-group-classic-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-group-classic-hung.svg)| hue:bulb-group-classic-hung|
| ![hue:bulb-filament-hung](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/bulb-filament-hung.svg)| hue:bulb-filament-hung|


### Want to help the community?
If you like what you see and want to help others discover this repo, please consider giving it a free star. Every one of the 183 custom icons has been driven by a community request just like yours and stars help other people find this repo.

### Want to get involved?
Its always good to see these icons being used. If you're proud of your dash, why not share a screenshot in the [forum thread](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource)?
